### ISSUE TITLE
Grid 2.9 improvements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1090]
- [ ] https://github.com/threefoldtech/tfexplorer/issues/302 
- [ ] https://github.com/threefoldtech/zos/issues/1322
- [ ]  https://github.com/threefoldtech/zos/issues/1324
- [ ] https://github.com/threefoldtech/tfexplorer/issues/331 paying X TFT per TB
- [ ] https://github.com/threefoldtech/zos/issues/1323
- [ ] https://github.com/threefoldtech/tfexplorer/issues/335
- [ ] https://github.com/threefoldtech/tfexplorer/issues/334
- [ ] research Kubernetes IP6 support for k3s. should have landed in 1.21 https://github.com/k3s-io/k3s/pull/3212
- [ ] farm power management of big farmers (todo)
- [ ] simple cli for farmmgmt  https://github.com/threefoldtech/tfexplorer/issues/332

**Comment by muhamadazmy** [comment]
Some concerns:
- Similar work need to be done for 3.0 so I would still say we should go to version 3.0 anyway, since it's toward the future 
- explorer code management is getting out of hand, this project was intended to be a temporary solution and was contributed to by many people to "hack in" features to unblock their pass.
- explorer was not "designed" to accept consumption reports from nodes regarding network or anything, so that's a new thing that need to be implemented on both zos and explorer side (more hacking on the explorer) which is not compatible with how pools work, and will make expiry calculations for the pool much harder and hairy.
- we also need to make the explorer (pause) or stop a workload on the node without a decomission. that's also now not supported, since the reservations received by the node from the explorer are either create, or delete. This is not gonna be clean to implement in a reliable way.

On the other hand, version 3.0 already have:
- Consumption reports is collected already per user (we still need to add networking)
- A standalone service that can be built to receive all capacity consumption and store it can be built
- Should be easier to implement pausing, since the node now is not polling, instead it implements functions over RMB, so a new message is sent to pause a network (either initiated by the farmer or the billing service)

What we don't have on 3.0
- billing
- A new k8s vm image since we already dropped the k8s primitive (but we do now have zmachine working with planetary network and public ips)

**Comment by muhamadazmy** [comment]
I will try here as part of the research state the amount of work to be done for both 2.9 and 3.0 in an objective way

|Feature|Version 2.9|Version 3.0| Comment|
|----------|---------------|---------------|--------------|
|Network Metrics per workload|Need to be implemented from scratch|Ned to be implemented from scratch| Its the same amount of work on both version, although it's not clear how to do it because there is no clear difference on the node between local and public traffic|
|Pushing the metrics to a billing system| Need to be implemented, but this doesn't fit the current model of how billing work since all calculation is done on the explorer by a mean of **predicted** depletion of the pool| Much easier to implement since this already fits the current model, since the node already collect consumption and push it __somewhere__ for billing| Version 2.9 implementation is gonna be hackish because currently the explorer does not allow this, and pools calculations are done completely differently|
| Explorer| The explorer in version 2.9 was a temporary solution until *bcdb* was ready, but since this never happened, explorer now is very hackish with so many layers of code that was implemented to fix issues that was not accounted to in design. Implementing network billing now won't fit how the pools work and will cause a lot of not foreseen issues| Not applicable, but we still need a place where we push consumption reports| |
| Pausing traffic in case of exceeding the limit| This is also gonna be very hackish and very hairy to implement because the node<->explorer communication is basically about reservations that needs to be either provisioned, or deprovisioned. Now we need to support other states where a reservation is paused but not deleted and then resumed later with another event| Node communication is done over *RMB* which supports implementing any functionality, hence a new function pause/resume can be added to be only possible to be called by an authority (the farmer may be) to pauser/resume the network| |
| Payments | This is already implemented in the explorer, and have been tested| Not implemented, and not clear what is gonna work here for this| |
| Blockchain | Not using the block chain, only users database on the explorer| Integrated in *RMB* for user identity| |

**Comment by xmonader** [comment]
we will continue with zos3
