### ISSUE TITLE
STORY: Uhuru Beta

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1125]
EDIT BY KEN: Story needs to be cleaned up.

- first beta of digital self based on nodejs
- features
    - zoom alternative = kutana
    - whatsapp alternative
    - gdocs alternative
    - integrated jimber browser
- uses QSFS for file storage
- communicate with Florian (Brasil) for design, don't go overboard, just make nicer
- under brand AYDO
- ygdrassil is network plane
- will live on top of primitives of 3.0

>> TODO: please link  to the right projects !!!

### AYDO specific requirements (In charge  @tobiaschielens )
Board:
https://github.com/threefoldtech/twin_aydo/projects/1
- [ ] share folders with chatgroups
- [x] threefold connect integration
- [ ] attachments of chats should be stored on a location visible in filemanager
- [ ] support playing of video
- [x] support pdf view
- [x] support for document edit

### Deployment requirements (in charge @jdelrue )

- [x] Build documentserver with unlimited users
- [ ] docker build script for document server
- [ ] docker build script for browser
- [ ] docker build script for twin
- [ ] Flist + Terraform Example how to deploy document server
- [ ] Flist + Terraform Example how to deploy jimber browser
- [ ] Flist + Terraform Example how to deploy digital twin browser

**Comment by jdelrue** [comment]
question: (KDS)
how do we deal with deployment of backend components like conference server (MTU), office server, browser server ?

My thoughts (JD):
For beta launch I would not focus too much on that and use a few central components for now. In next version we have to really consider what is best.

For MTU probably starting one per meeting is the easiest solution, on the DT of the host. 

For documents you only need one at the moment you access the document. Could also be started on the DT of the host altough its probably a bit more overkill... Still not sure about this one.


Browser server we would need now, and probably deploy a battery and do some load balancing. BTW: For meetings we cant use the browser yet but since the component will be on the general internet for now this is not really a problem.

**Comment by sasha-astiadi** [comment]
will review the user flow and brandinfg with florian. will be minimal improvement.

**Comment by sasha-astiadi** [comment]
@ken-de-moor Check mobile usability?

**Comment by sasha-astiadi** [comment]
@ken-de-moor prepare aydo repo and project

**Comment by jdelrue** [comment]
Screenshots of new version:

![image](https://user-images.githubusercontent.com/1687505/129696099-15aeb173-0be4-493d-810d-492eb7327915.png)


![image](https://user-images.githubusercontent.com/1687505/129696157-dbf6ba7a-63e2-48bb-b16a-f708321f944b.png)




![image](https://user-images.githubusercontent.com/1687505/129696132-9b453da5-b163-42f1-a821-938596e87900.png)

**Comment by ken-de-moor** [comment]
Old version of the ticket with old requirements and is live for months already, will be creating new project boards with actual features being worked on, and closing the existing project board.
