### ISSUE TITLE
STORY: Farm view adjustments on TFGrid Dashboard

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1212]
## Maintenance/Fixes

TFGrid Dashboard allows the user/farmer to manage the farms he created
It seems that some slowness can be observed while displaying the farms information
It also would be relevant to hide some unnecessary information (could be the cause of the slowness?) and to enable a delete farm option

## Story items

- Repo [TFGrid Dashboard](https://github.com/threefoldtech/tfgrid_dashboard)
- Technical issues
  - [x] Unexpected slowness in farms view
    - [x] Why is it so slow to show farms/nodes (shouldn’t that come from the postgresql so be fast?)
    - [x] Check why 3Nodes from a given farm don’t popup sooner (shown after initial install)
 <strike> - [ ] Unnecessary farm view information
    - [ ] No need to show certification status (there is no certified now), twin id nor pricing policy
  - [ ] Delete farm option (?)
    - [ ] Allow farms to be deleted
    - [ ] Make sure to warm the farmer about the consequences of the removal 
 <strike>

**Comment by renauter** [comment]
Re-opened this issue because it seems to be clearer to deal with small adjustments of TFChain Portal separately

**Comment by DylanVerstraete** [comment]
> Delete farm option

I would not add that, not that it's technically not possible, it hasn't been tested with +5000 nodes in the system. Since there is no lookup between a farm and it's nodes we need to iterate over all the nodes in the system and also remove those that belong to a farm which can cause block production to be stalled if not completed within time bounds.

**Comment by renauter** [comment]
I agree, mainly because we shouldn't delete a farm with some nodes on it
So would it be possible to delete "empty" farms? 

Complementary question:
Is it possible to migrate a 3node from a farm to another?
In a soft way I mean, without having to reboot the 3node with the new farm config (imagine I have an ongoing workload on it)

**Comment by renauter** [comment]
Updated issue as adjustments should be redirected to new TFGrid Dashboard

**Comment by xmonader** [comment]
suggestion from @LeeSmet: for deletion at least we can delete empty farms.

**Comment by DylanVerstraete** [comment]
We cannot delete "empty" farms. The chain does not know about the relation between a farm and his nodes. So it's impossible to check if a farm is empty before deleting it. https://github.com/threefoldtech/tfchain/commit/29d9075dcb44dad1c06a18e5037bf995d77ebd49 was added instead

**Comment by xmonader** [comment]
to be followed in another story for farms deletion  https://github.com/threefoldtech/tfgrid_dashboard/issues/178 , as for the rest, all is done

**Comment by A-Harby** [comment]
Node or farm loading times are acceptable in dev, test, or qanet but noticeably slow on the mainnet.
is their is any specification for how this measurement should be computed?

**Comment by mohamedamer453** [comment]
Verified on devnet.

Farm/nodes tables loading performance on devnet  is fast and acceptable, and the same goes for node/farm details.
However the main performance issue was on mainnet since the number of nodes/farms is much higher than devnet. but unfortunately the performance on mainnet cannot be verified until the latest version of the dashboard is deployed there.
