### ISSUE TITLE
STORY: Decentralized node sales

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1217]
The aim is to provide a mechanism for resellers to register nodes on the chain for selling and for users to be buy these nodes

## as a seller
I should be 
- able to register a node for sale on the chain
- able to set the price in TFT
- node specs to be automatically be picked up

## as a buyer
I should be
- able to browse available nodes for sale
- buy a node with TFT (should be in an escrow that gets unlocked once the node is received and booted with the specs at the buying time) -that's a technical detail, but if there's another way it should be fine)
- somehow track the order e.g (shipping service order link)
- I should be able to rate the buyer (With a comment)

## notes

- Once the user receives the node and boots it with the information that the seller bundled, the chain should recognize the node, unlock the tokens and send the money to the seller, if it takes too long e.g 3 or 6 month? -should be defined in the contract- the money should get transferred back to the user. 
-  Rating the seller would open up the possibility of tagging them as certified sellers based on the users feedback

**Comment by xmonader** [comment]
cc @DylanVerstraete @LeeSmet

**Comment by LeeSmet** [comment]
So the main concern I have is the lack of central authority also makes it difficult to establish some kind of abuse prevention scheme. As it stands, this can be abused by either party. Next to this, if we assume both parties are honest, there is also the scenario where something goes wrong in between, i.e. mostly during shipping. Even if we assume honest parties, it is another thing to assume a second party will actively cooperate with another party to recover missing or damaged goods, if said party does not stand to gain anything from it and will also not lose anything from it (as at this point he invests time and possibly other resources while not gaining a return, therefore the expected return of this action is negative in value). Small overview of immediate issues:

## Abuse by seller

We start with a regular flow. The seller sells a node and gets the shipping details from the buyer. After this, the buyer transfers the TFT to an escrow account. At this point, the seller would normally ship the node. However, he can now simply boot the node himself with the farm id of the buyer. The escrow will unlock, so the seller gets the TFT, while he still has the hardware himself. After receiving the tokens, he powers off the node again, wipes it, and puts it up for sale again. The buyer lost his TFT and has no node.

## Abuse by buyer

Similarly this flow starts of normal. Buyer buys a node from a potential seller, sends money to the escrow, and conveys his shipping details to the sender. The sender then prepares the node and ships it to the buyer. At this point, the buyer can:

- Boot the node in a different farm
- Wipe the node and boot it in his farm, thereby removing the node id. In this scenario, we could still use on board data like serial number, however this is really unreliable (and requires to be set in the first place).
- Wipe the node and install another OS on it
- Not boot the node until the escrow expires and returns the funds. Then boot it in the farm.

## 3rd party issues

There are also potential issues with third parties, mostly shipping companies. Firstly, since the proposed model doesn't give the tokens to the seller until the buyer successfully connects it, it is only the seller who puts up a risk, and therefore is enticed to take action. If a node is delivered at a wrong address, the buyer has no incentive to go and look for it, other than the locked tokens might decrease in value until they are returned. Secondly, if the node is stolen in between the buyer and seller, then it is all on the seller to recover it. This is particularly bad if it is an international shipping, as the node might be stolen in the country where the node is delived, and as such the seller would need to work with foreign law enforcement.

**Comment by xmonader** [comment]
@despiegk please read

**Comment by despiegk** [comment]
as discussed yesterday 2 suggested solutions

1. buyer needs to sign for reception of the nodes this resolves first issue of abuse
2. we should create a sort of mediation council to help when issues arise in the process, we do realize this adds a more centralized component to it but for sure it's less centralized than what we do today. This Mediation Council can be rewarded from a fee of e.g. 2% on each sell which then pays for the people investigating what happened e.g. was the good shipped, was it an error, ...  We will probably need this for other usecases as well e.g. wrong content on our grid.

**Comment by Nelson361** [comment]
Hey, before I pull out my soapbox and go over how some of these proposals would be disastrous to me (Duck Farm Data), I want to clarify that we are discussing revising the current certified node sales system on the Marketplace?

**Comment by xmonader** [comment]
moved to 3.8 @LeeSmet and @despiegk should discuss
