### ISSUE TITLE
Minting A7 - need detailed spec

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1241]
Needs to be done on the sidechain directly (TFChain Substrate), no need for stellar address.
Farming DAO for TFChain (voting in line with size of farm)

lee

**Comment by LeeSmet** [comment]
We first need to see what is going to happen, are we abandoning stellar in favor of cosmos? also, as said, tfchain is a side chain, the current setup does now allow for minting on only the sidechain, since we vault on stellar. If we end up doing minting on tfchain in this scenario, we will need to mint on the bridge account on the stellar side as well. TL DR: needs info on the global chain setup

**Comment by LeeSmet** [comment]
Blocked until more input is received
