### ISSUE TITLE
Need to make sure workloads don't get deleted immediately when there are no funds in wallet

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#1243]
Is there a way to make the workloads on a deployment unaccessible on a time sensitive base (e.g. a month) if the wallet does not have any funds on them? After the month it can be deleted. 

Problem is that right now if there's an issue which causes a wallet to get drained (which happened already in the past), all deployments get deleted without warning.

**Comment by LeeSmet** [comment]
If a user can't pay for a workload anymore, we want to make sure he can't use it, yet it should also not be completely removed immediately. To achieve this, user facing workloads should be made inaccessible. From all the workloads we have, we have only 3 actual user facing ones which are paid, being container and VM, and 0-db. It suffices to just make these inaccessible in a reversible way. 

Technically, we can achieve this as follows:
- Implement a workload "pause" state on zos, at least for the above mentioned workloads. For containers / VM's, we can use the CH api to simply pause them. For 0-db, this is not possible, though since 0-db only does something when it receives a command, we can disconnect the link or something similar. 
- We introduce a new state on contracts on chain, `grace_period` (or similar). This state memorizes the block it entered this state.
- When zos notices a grace period event for such a workload, it pauses the workload instead of deleting it. If a contract Cancelled event is noticed, it still outright deletes it.
- In TFChain, the code path which currently does a cancel for out of funds reason is modified to put the contract in the grace period state, with the block number in tfchain.
- Grace period contracts remain in the billing loop. When a contract in grace period is billed, a check is done to see if the grace period has elapsed (lets say 2 weeks for example). If it is elapsed, the contract is moved to the cancelled state for out of funds reasons. This way zos can delete it (should not matter if it is paused or not). 
- If the contract is billed while in grace period, but not sufficient funds are present, the debt is accrued in the state.
- If sufficient tokens are added on the account, the debt is cleared, tokens are "billed" for the debt, and the contract is moved to created state again.
- Zos then unpauses the workloads


In the future, we can see if we can do something with an "on transfer" hook if possible to immediately unpause the workloads, though this is only an optimization

**Comment by DylanVerstraete** [comment]
TFchain Deployed on devnet

**Comment by despiegk** [comment]
this story is not finished 
please provide link to documentation so we can see its all properly documented
also how can people know they are in this state?
what happens if it happens, how long do we keeo it... all needs to be in doc

**Comment by DylanVerstraete** [comment]
Docs to be added https://github.com/threefoldfoundation/info_manual3/issues/132

**Comment by xmonader** [comment]
https://github.com/threefoldfoundation/info_manual3/commit/9f4666f5bfbf9c89972f8881429cc09b451f863c
