### ISSUE TITLE
DISCUSSION: L1 / TF-Chain Validator nodes 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#1258]
### Definition of the Need

Given the fact that 
- TFChain is currently running on 5 nodes in 2 locations
- health of the Lochristi nodes and DC in general is not optimal
- if DC in Lochristi goes down, risk that TFChain stops working

There is an urgent need to decentralise the TF-Chain and run many more L1 validator nodes. 
To make that happen we need to incentivize L1 validators to run a node. 

### Path to get there : 

- [ ] Ask L0 validators to step into the L1 validator program and run TFChain nodes
- [ ] Ask the same staking of TFTs (50k, 100k, 150k), but then on TF-Chain, and reward them using what has been defined for L0
- [ ] Up to 100 nodes to be accepted
- [ ] Make a workload with a TFChain node available, similar to the plan for L2

### Alternative

- [ ] Make running a TFChain node part of the requirements for Gold Certification

### Timing

ASAP : if hot summer, risk on Lochristi DC

**Comment by DylanVerstraete** [comment]
TFChain is not configured as an open network where anyone can join and run a validator. It used POA (proof of authority) and this is a slot-based consensus. When we potentially accept 100 validators to be ran by the community a lot of nodes will go down (due to bad management) and will miss their block production slot and will slow down our chain considerably. 

We also don't have a reward pool to incentive users to run validators, since this is a very costly operation the rewards need to heavily outscale the cost. We also don't have a slashing mechanism that punishes bad behaving validators (low uptime, bad block production, ...). All in all, it's not possible right now with the current state of tfchain.

Solution would be is the switch consensus from POA to NPOS (with staking / slashing) built in. It would also be good if a large percentage of cultivation (smart contract billing) would go towards these validators in the npos network. Additionally a large reward pool should be set up with an initial amount to reward validators.

**Comment by LeeSmet** [comment]
slot based consensus is not relevant, the POS implementation we had was also slot based. But now that we launched a POA network, we **can't** change it anymore. That is, technically it is possible, though even the people at paritytech claim that in the current state of things it will involve black magic and arcane rituals (you can google for the relevant issues if interested). So basically running POS as consensus is not an option anymore.

As for rewards, the only feasible thing would be to have the foundation pay out the rewards (or the treasure once implemented), though that likely also won't happen (as it relies on the foundation having sufficient tokens and be willing to give those up). So basically an L1 validator will be on a "thx  for doing this" basis.

Note that the reward problem is also there for L0 and L2 validators, just saying that they will get some rewards is one thing, specifying where that reward comes from is another (specifically yield on staked tokens). As it stands this is undefined, and we can't just make new tokens as tokens are only created through minting for capacity.

**Comment by DylanVerstraete** [comment]
It's not only rewarding that is the issue but also punishing if the validators behave badly. This is not a standard feature and will require a lot of work to get it done properly.

**Comment by gmachtel** [comment]
OK then the easiest option for now seems to be to add "Run a TFChain node" as a requirement for gold certification. have added it as an alternative option.

**Comment by LeeSmet** [comment]
Realistically very limitted farms will even meet the conditions to get Gold certification as they are right now, and even _if_ they all apply and are willing to do this, which is a lot less than what the aim is here.

Also, the way validators on tfchain have been envisioned in the current iteration is not with a stake, but with a manual approval process from the council. Having both will be tough to manage.

**Comment by DylanVerstraete** [comment]
> And, if we require it for gold certification, do we have now ability (mechanism) to automatically deploy TFChain node on farmer dedicated 3node ?

Deploying and managing a TFChain validator cannot be automated, it will always require work and configuration from the person deploying it.

**Comment by LeeSmet** [comment]
So after doing a bit of initial research, there is an option to run NPOS (though I would remove the fact that validators need to be approved in that case). This is possible because NPOS is an election mechanism and is not tied into the actual block production/validation. Although we previously ran NPOS on BABE, we can run NPOS on AURA as well.

## Current situation

First of, it should be noted that traditionally, validators simply collect transaction fees for their incentive, + a possible block production reward. We don't have the latter and the transactions fees will always be small as tfchain is intended to be a side chain which is only used to spawn the contracts.

Current distribution of contract payout is as follows:
- 50% certified sales channel, to be replaced with the treasury or an approved solution payout account in the upcoming tfchain release in a7
- 35% burned (this should arguably be more, though lets not get into the tokenomic side of things here).
- 10% to a foundation controlled account
- 5% to an "NPOS reward account". This is a leftover of the NPOS implementation we tested earlier.

It is the last account which is of interest.

## Possible future

We can (once again) implement NPOS as an election mechanism for authorities. In this scenario, we can fork the existing pallet provided by substrate, and make modifications to properly suit our needs.

### Out of the box this gets us

- Staking (adding collateral to your own node)
- Nominating (adding collateral to someone else's node)
- Periodic election (one set of validators is active for an era, at the end of every era a new set is elected which will validate for the next era)
- Era based rewards. For every block produced, points are awarded. For every uncle produced, a small amount of points is also awarded. As we use AURA, uncles are not relevant. At the end of the era, a payout is calculated, and distributed over all validators based on how much points they scored. Payout separation between staker and nominators is done automatically based on a configurable commission percentage for the staker, and the remainder is divided pro rate according to the provided collateral.
- Slashing of collateral for misbehaving stakers, depending on the type of misbehavior (missing nodes are punished less severely compared to malicious nodes)

### Features we don't want

- Inflation. The reward is based on an inflation curve, as traditional NPOS makes new tokens for validators. We don't want this.

### Possible changes

- Offline detection. In BABE + NPOS, a node is detected as offline if it does not make any block for a whole session and it misses an off-chain "Im online" message (if configured). Once a node is detected as offline, a quicker era rotation is triggered which puts a new validator set in power without the offline node (which will also be punished). The problem here is that this means you potentially go an entire session without this validator. In BABE this can't be solved since the randomness of block creations means you can't be certain someone mist a slot (as proof that he is authorized to submit in a slot is only provided when the block is submitted, i.e. there is positive proof but not negative proof). Validators which missed blocks but are online at some point still get "punished" by not having as many points, which in turn results in a lesser payout. In AURA, slot assignment is fixed for a validator set. Therefore we immediately know if a validator missed his slot. We could say that a validator can only miss X amount of slots in a session (or consecutively) before marking it as down and triggering a reelection. This increases chain durability since there is much less chance that random nodes going down compound to result in less than 2/3 of all validators being online.
- Reward payout sourced from reward account. 5% of contract payout is collected (currently). The idea would be to take 10% (for example) of this pool per era and distribute it over all validators (pro rate earned points in era). By taking only a fraction per era, you avoid differences in era being too big because someone cancelled a lot of workloads, ran out of tokens, started a lot of workloads... As grid utilization converges to some amount of value over a given period, eventually the payout for validators will converge to the percentage of this value as configured

## Notes

- By using AURA instead of BABE, a validator can potentially submit txes only in his own slot, thereby recuperating the tx fee he spend. Since we consider tx fees to be almost 0 (especially compared to contract fees), this is not an issue.
- Reward payout account as it is should probably be reset to avoid giving too much to initial validators. Ideally the tokens are burned to reduce supply
- If we don't go for NPOS we should add the 5% NPOS account to the burned amount for better tokenomics.
- As the grid grows in usage, and thus the requirement for more validators grows, the value in the reward account will increase, resulting in an increase in payout, resulting in more incentive to run a validator and secure the grid.
- If initial value in the account proves too low, the council could invest funds from the treasury periodically until the reward account is self sufficient from used capacity.

## Important caveats

- A lot more research is needed to vet the above, this is only an idea for a possible solution based on prior knowledge and spending 2 hours skimming through assorted docs.
- Implementing this (especially on a live chain) will require **a lot** of development work, not to mention **even more** testing.

**Comment by robvanmieghem** [comment]
This is currently being handled by the council which (dis)approves validator appications

**Comment by robvanmieghem** [comment]
and the main chain has enough validator nodes at the moment
