### ISSUE TITLE
STORY; POC wallet + TFConnect : Key derivation multi-blockchain example.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1268]
CONTEXT: This is a demo/POC , see https://github.com/threefoldtech/demo-chains-js

This is not integrated in TF Connect yet, the thing is purely to make a POC where you can create wallets on several blockchains. How it is going to be implemented and where is still to be decided.

We want an example webapp where you can login with TF Connect and multiple blockchain wallets are derived.

For each blockchain the following actions need to be available : 
- Show balance.
- Show private key
- Show address
- Create wallet ( happens automatically ).

For the following blockchains.

- [x] Stellar
- [x] Substrate
- [x] Binance
- [x] Algorand
- [ ] Cosmos

**Comment by sasha-astiadi** [comment]
ETA: End of month, 3.6.1
new repo: please link @ken-de-moor

**Comment by ken-de-moor** [comment]
Binance/algorand finished, going to wait with cosmos and descope it for this release since it's more work and we already have 4 examples now.

**Comment by ken-de-moor** [comment]
Repo: https://github.com/threefoldtech/demo-chains-js

**Comment by sasha-astiadi** [comment]
@ken-de-moor @xmonader have a call with @LennertDefauw1 to talk about the implementation please

**Comment by xmonader** [comment]
After carefully checking what was delivered there're a few issues, that been discussed already with @LennertDefauw1 @LeeSmet 
- It gives a seed not related to a wallet that exists on the threefold app
- from the seed, you can generate the keypair for stellar, tfchain, but the wallet is not activated or funded, so that will be done manually, which just added more complexity not making things simpler

## the expected flow should be:
- I have a wallet (created in threefold connect app), activated, funded, ready to use.
- i can specify that i want the seed for a wallet during the login and the user approves it
- the app shares the seed with the website 
- the website can load the keypair and use it to get the get the wallet, transfer money, do signing

**Comment by ken-de-moor** [comment]
Extra requirement if we're going to expose wallet secrets in this flow, since this is a major social engineering security risk.

- UI needs to be extremely clear and warn that if the user accepts it, they hand over full control over the wallet.
- It needs to be super clear specifically what wallet they are handing control over for.
- This needs to be a separate flow of other shares that do not hand over control over your wallet. It can not be grouped in with other data requests, otherwise they used will get used to just pressing "agree".

**Comment by robvanmieghem** [comment]
Why would we share the secret?

**Comment by ken-de-moor** [comment]
Closed in favour of https://github.com/threefoldtech/home/issues/1296

The demo example is finished, the key sharing what it was re-opened for can be seen in issue 1296
