### ISSUE TITLE
FreeFlow Twin beta V1.5

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1275]
Uhuru version: https://github.com/threefoldtech/twin_aydo/projects/10

- Bug fixes
- Tagging people in chats
- Improve dev setup
- Improve staging+production link setup.
- Self-deploy improvements.
- PWA support
- Add info labels
- HTML encoding of messages
- Overflow handling
- Remember login session
- File upload progress
- Link preview
- Adding more search options

**Comment by sasha-astiadi** [comment]
already been worked on, but new prio is to rebrand to freeflow

**Comment by ken-de-moor** [comment]
Rebranding is done, finishing up the release right now. I have about 45 verification issues to go through.

**Comment by despiegk** [comment]
need to organize a call with the architects of this to discuss

- how is network setup, please point to an diagram (if you don't have one use mermaid to create one in right repo's)
- where is code, make overview
- why do we keep on losing data?
- why can't we use kubernetes internal networking when we are in 1 cluster between e.g. frontend and document server
- where is documentation of the api and how does it communicate to each other
- need to discuss architecture how people can deploy their own kubernetes cluster for freeflow twins and then do communication in between
- need to discuss how people deploy their own on TFGrid
- discuss how people (twins) can find each other, even over clusters if there are multiple
- discuss team, who does what

discuss some future elements
- there is no need to use rmb, we are going to next version of it, RMB gets integrated in tendermint/yggdrasil
- should we stay with kubernetes, is not 100% in line with idea if being independent

remarks
- please document all of this, architecture, roadmap, how to deploy, ... in mdbook format see https://github.com/ourworld-tsc/ourworld_books how we use it

**Comment by jdelrue** [comment]
- how is network setup, please point to an diagram (if you don't have one use mermaid to create one in right repo's)
-> Will do, but everything is peer to peer yggdrasil so its pretty simple :-) 
- where is code, make overview
All code is here https://github.com/threefoldtech/twin_aydo
- why do we keep on losing data on test env?
This was as designed because we were not doing migrations, but it has changed since yesterday. Data will not be lost anymore
- how can we run a much larger testenv on TFGrid
Yes, @LennertDefauw1 is creating a weblet so we can run it on TFGrid
- why can't we use kubernetes internal networking when we are in 1 cluster between e.g. frontend and document server
Everything is really relying on Yggdrasil for communications, encryption and host detection so it would mean a pretty big change and less decentralized outcome.
- where is documentation of the api and how does it communicate to each other
Will check with the team, we started on specs on the protocol but dont think its finished
- need to discuss architecture how people can deploy their own kubernetes cluster for freeflow twins and then do communication in between
Why Kubernetes? 
- need to discuss how people deploy their own on TFGrid
This is ongoing, @LennertDefauw1 is creating it
- discuss how people (twins) can find each other, even over clusters if there are multiple
It just works because we use Yggdrasil
- discuss team, who does what
Ok

**Comment by ken-de-moor** [comment]
Release is done and live, closing ticket but will link back to it from the new ticket since there is still important comments on this ticket.
