### ISSUE TITLE
STORY: new QSFS version (for TFGrid v3.9.0)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1277]
- QSFS can use some more testing
- need to understand better how to use in Kubernetes, VM, …
- need to check the edge cases & document if changes are required
- example script how to deploy Minio on top of QSFS

**Comment by maxux** [comment]
If Minio is used only to provide an S3 interface on top on QSFS, it works (we already did it successfully), but it's **extremely** inefficient.

Minio uses a cache directory on which it stores all data chunks before building the final file by concatenating all chunks together. By using `QSFS` with default behavior, this is a 100% size waste (file is stored 2 times on the backend). There is a workaround by mounting the `temp` directory to a local disk and not over `QSFS` to avoid this but this present more things to take in account when deploying a solution.

So it's doable, we did it already, if we need a **quick** working solution it's fine, minio have the advantage to support more protocols and have a nice UI on top. But if we want to support S3, it would be really interesting to build something on top of `0-db` directly and use the full power of `0-stor` without overhead.

**Comment by maxux** [comment]
I'm going to do some research on that anytime soon :)

**Comment by xmonader** [comment]
moved out from 3.7 to 3.8

**Comment by scottyeager** [comment]
Would be nice to see self healing features back on the roadmap, and some other thoughts:
* Is self healing possible without an external daemon? Can TF Chain itself handle provisioning new zdbs if some go offline?
* Should be able to maintain an "x of y" redundancy scheme across a set of prespecified nodes
* Maybe under new provisioning schemed for wake on LAN, this becomes easier since contracts are with farms rather than nodes?
* Currently an existing QSFS can't be mounted to new VM. That probably needs to change so data can be recovered on a different VM
* QSFS support in the playground

Someday dreams... a mode where data is never lost, as long as the provisioning wallet has some TFT and there are some node alive *somewhere* on the Grid. A kind of "set and forget" that doesn't depend on specific nodes or farms, can provision to new nodes that come online, even new farms. This probably is the realm of external daemon, like the twin, that can handle provisioning new capacity on behalf of the user

**Comment by despiegk** [comment]
first need to do https://github.com/threefoldtech/home/issues/1345

**Comment by despiegk** [comment]
about self healing, I believe there are some as part of the zstor...
need to have more details
