### ISSUE TITLE
story: hub improvements

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1292]
## hub.grid.tf improvements 

- login with private key of TFChain (so its seamless integrated with dashboard/portal)
- same color scheme as portal
- see how to make data redundant and run on at least 2-3 locations
- see how to sync the data and keep same on 2-3 locations

**Comment by despiegk** [comment]
idea: is ipfs fast enough to serve the files itself? if yes we will have our IPFS pinning service in future, means data could come from IPFS directly from ZOS

**Comment by xmonader** [comment]
> login with private key of TFChain (so its seamless integrated with dashboard/portal)
the hub requires usernames (consistent ones) to be used to namespace the flists. in the polka extension you can give your keys any name, and in different browsers. I don't think changing the login will help.

**Comment by maxux** [comment]
First, the production zdb needs to be updated to latest version. Current version is still running zdb 1.x not supported nor maintained for years now. In order to get any working replication or feature to do some, we need to move to 2.x.

I already have utility to do that and have in addition some script to cleanup a bit the database by discarding non-used chunks anymore.

Does the `color scheme` point only consist to adapt color scheme or does the full template needs to be changed ?

**Comment by maxux** [comment]
Latest commit to zdb allows a better master-slave support, to get stable replication across multiple sites.

**Comment by sasha-astiadi** [comment]
irrelevant to project 3,.8 will remove
