### ISSUE TITLE
TFConnect key management

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1296]
Aiming to simplify the sources of wallets and the key management the suggested flow as follows

- The user goes to a website
- the website does the auth flow with TF Connect to get the username and wallet(s) secrets the user is willing to share to load in the frontend 
   - the wallets could be existing or the user can create one in the phone app directly (the phone app needs to make sure it's activated and funded)
   - the phone app shares the secret of the generated wallet with the website

## notes
- sharing a non-funded/inactive wallet keys from TF connect doesn't make sense, because they will be activated eventually by the website (and it has the secret already) so it has no security benefits over sharing an activated wallet 
- 3rd party websites shouldn't be concerned about the activation, it can be already done in the TF connect app, and again there's no security benefit of not activating it. (as you already have shared the secret)
- the UI needs to show warnings if the user is sharing a wallet with e.g balance > 10000 TFT for instance, and suggest to create a wallet that the user can fund with small amounts maybe.  

## remarks
- The generated wallets are for the supported chains e.g stellar, tfchain and they need to be activated
- WalletConnect been discarded (doesn't seem functional for having tons of transactions being executed)

**Comment by xmonader** [comment]
@robvanmieghem @despiegk @jdelrue

**Comment by jdelrue** [comment]
We are not really in favor of sharing existing / new wallets:
- User can easily be scammed into sharing an existing wallet with loads of TFT on it, which can then be stolen. 

- Sharing keys puts the responsibility of making / managing wallets with the 3rd party application, we do think it makes more sense. We are,however, not really in favor of the "named key" system since this can still be scammed, which is not the case if we only redirect to the correct domain name. This way only the same domain can get the key. If the key needs to be shared over multiple domains one central domain can used to fetch the key, and the key can be only shared with the correct domains.

- Wallet connect-ish system will be some work but is safe


As mentioned, we can make whatever you guys ask we are just concerned about user security.

**Comment by ken-de-moor** [comment]
Can no longer be 3.7 due to no timely feeback.

**Comment by despiegk** [comment]
indeed dangerous
