### ISSUE TITLE
Improved Capacity Planning

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1304]
Required for #1303 to be able to gradually consume capacity from the farm nodes one by one or group by group, instead having active workloads on all of the nodes, which prevents the farmer from turning off the nodes to save power bills. the main idea is the farmer can split their resources into hot/cold capacity pools. and provisioning should get its resources from the hot capacity pool first until it's consumed (or about to get consumed) and then it can turn on few nodes from the cold capacity and assign them to the hot capacity.

**Comment by despiegk** [comment]
no need for farmer to do anything, this needs to be done by us as part of our provisioning solution,
we should deal with a farm how we deal for finding a node

once a farm is used, we have logic how to define in the farm which node to use based on which resources required and which nodes are operational

**Comment by DylanVerstraete** [comment]
In 3.8.x tfchain will introduce a storage map where nodes of a farm are mapped, this can greatly help us with capacity planning.

When creating a `NodeContract` instead of providing a `node_id` a `farm_id` can be provided, the chain can then check for all the nodes and their used resources (since it knows about contracts on all nodes). Then it for example can calculate which nodes to pick but onlt if on contract creation the user would also specify the wanted resources. This is now reported by the node once the deployment is sent to the nodes. So we might need to change the contract creation api to the following:

create_node_contract:
- Farm ID
- Resources

With this data we can do proper capacity planning but it will also require some reworking in zos. ZOS should check the deployment once it's sent by the user if it indeed requested this amount of resources. If the user requested more resources on the node than what is saved on chain the node should return an error. 

This contract creation operation on chain might be a heavy calculation if the farm has a lot of nodes. since it would need to iterate over all the nodes on the farm to select the right node to deploy on. 

## Problems

What if a user wants to deploy in a HA way on a farm? The chain in this case would always select a node that already is in use, therefore the deployments will end up on the same node. I think the chain should also allow a user to select a specific node if he does not provide the farm id.

**Comment by xmonader** [comment]
For me I prefer the 2nd approach to be on the client side that way

**Comment by sasha-astiadi** [comment]
any decision made @xmonader ? shall it be on 3.8 or for later

**Comment by sasha-astiadi** [comment]
https://github.com/orgs/threefoldtech/projects/186/views/1 the agreed solution with checklist and todos

**Comment by xmonader** [comment]
could on chain should be finished by 23-11, will start the clients updates as soon as possible

**Comment by xmonader** [comment]
closing in favor of #1371
