### ISSUE TITLE
TFGrid: more userfriendly weblets (no need for browser plugin)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1343]
## goal

- make it super easy for people to use weblets

## requirements

- no need for browser plugins
- no need to use dashboard
- easy to transfer TFT from TFConnect
- easy to see your workload metadata
- workload metadata is stored in TFChain (so cannot be lost)
- ssh key easy to manage

## outdated info

see https://github.com/threefoldtech/home/blob/master/wiki/specs/unified_login_metadatastor.md

> todo: remove or update info

**Comment by xmonader** [comment]
main problem now is we use the local storage password (to unlock the user profile) also to be the key to store the metadata, if we care about the current deployments we should allow ppl to to migrate their workloads with an intermediate release where only the mnemonics (or a derived password of it) to be used as the kv store encryption key to store the metadata about the deployments. If we don't really care about that we can enforce it to be the just the mnemonics and a single profile to be used for now.


Changing to support the extension requires updating weblets and the dashboard which is fine, but we are also in the middle of updating them for types changes, contracts updates, and deployments updates.

## extension 
### extensions storage

they have a similar localstorage api interface https://developer.chrome.com/docs/extensions/reference/storage/

## behavior on websites
the extension needs to show a clear warning on sites not managed by threefold, and enforces the users approval on signing, otherwise, anyone can ask auto signing malicious code.

**Comment by A-Harby** [comment]
Verified on weblets, Devnet, 5ef6de6.

Profile manager is added and now user doesn't need password and profiles to use site.
Only mnemonics which can be create from weblets itself (no need to use polkadot extension and dashboard portals),
Easy to create account, transfer TFT and create ssh keys.
![image](https://user-images.githubusercontent.com/109473873/214071217-0a27eb0f-57b7-45c2-a333-891519e764ae.png)
