### ISSUE TITLE
mastodon deployment

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1349]
- mastodon 4
- email as authentication for mastodon
https://github.com/threefoldtech/grid_weblets/issues/1080

**Comment by mohamedamer453** [comment]
Verified

A separate mastodon weblet was added and it's available on https://getmastodon.threefold.io

The weblet is fully functional and a lot of fixes/improvements were done since it was made and more fixes improvements are being done in  https://github.com/orgs/threefoldtech/projects/194/views/9

The weblet introduces a new flow were the user is able to create a twin on the grid a generate a ssh key pair directly from the website without the need of anything else. from there it's a matter of minutes to getting a mastodon instance up and running.

and also other tools like Code-Server and Webmin are available for each instance for configuration and monitoring purposes.

and login options are either through email and password or through ThreeFold Connect.


A Test Suite for mastodon was created on [testlodge](https://app.testlodge.com/a/26076/projects/40893/suites/217977) with cases/scenarios testing all the components of the weblet
