### ISSUE TITLE
TF Notary

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#135]
In the [grid lanuch storycard]( https://github.com/threefoldtech/home/issues/101 ), a user creates a reservation transaction, a central robot that watches out for any new reservation transactions and creates the required workload and returns the relevant information back to the user.

The TF Notary will serve as a store for schema requests made by users when reserving capacity. When the users requests capacity, it will first save the schema of the request in the notary BCDB, then use the key of that entry in its reservation transaction in the blockchain.

The reason of this new "Notary" component is to be able to already have a close flow for the reservation to what is going to happen once the 3bot will be live on the grid. Now we have 1 central robot and 1 notary. Once 3bot will be in the picture, each 3bot will serve as notary and deploy the workloads

### Goals:
 - Any user should able to register info to the TF Notary 
 - Maximum info size should be 1KB ( proper value to be defined)
 - if for any reason the info is bigger than 1KB, store in 3bot and only register the metadata about how to get to data in the TF-Notary ( probably not needed)

### Requirements
 - Three methods:
    - **register**
        - properties:
                 - 3bot ID (from the blockchain, see [here](https://github.com/threefoldfoundation/tfchain/blob/master/doc/3bot.md#3bot))
                 - content
                 - signature of content with private key of 3bot (from blockchain)
         - actions
                 - Notary will check that signature is inline with 3Bot ID provided, meaning the Notary verifies that the 3bot with the ID sent has indeed created the info.
                - Info gets stored in BCDB
                - black2 Hash of the content is return
    - **get**
        - properties:
               - key
        - actions:
               - will return info to anyone, no security. If key is known, info is returned
        - returns:
               - content
               - last update time of content
               - signature
               - 3Bot ID of author

 - Backup to S3 (Restic)

### Technology used:
 - JSX
 - GEDIS interface (seamless client in python for remote use)
 - Openresty get/set/delete REST interface, use redis interface below to GEDIS
 - Stored in BCDB
 - Master/Slave on ZDB level (2 slaves)

**Comment by LeeSmet** [comment]
Some ideas:

- Having a user choose a key does not really add any value I think. Imho it would be better for the user to upload the data, then have the server generate a key, which is then returned to the user. As a key, it seems that a strong hash might be the best option, since it allows for an additional validation step to check that the data has not been modified after the inital post.

- For a hashing algo, it'd say something like BLAKE2b. This is also being used in rivine/tfchain for the hash of the data before a signature is created. Furthermore if the signature is to be verified in the server, either a fixed hashing algo is needed, or the ability to indicate a hash algo if multiple should be supported.

- If a hash is returned then the data format needs a variable field, to allow a user to set the same data twice (for e.g. reservations), and get a different hash. I'm thinking the server can add a `created` field or similar, with a unix timestamp. This field can then not be tampered with since the hash is returned, so a later change would be detectable if a client gets the data and hashes it again. This limits clients to sending the same info once every second but that should be fine.

- delete action does not make much sense I think, if we get a key and store that in the blockchain to make a reservation, the key is there forever, so it makes sense to me that we don't allow users to delete their data after a week.

**Comment by rkhamis** [comment]
> Having a user choose a key does not really add any value I think. Imho it would be better for the user to upload the data, then have the server generate a key, which is then returned to the user. As a key, it seems that a strong hash might be the best option, since it allows for an additional validation step to check that the data has not been modified after the inital post

agree. me and @zaibon already talked about it and I think we both feel more comfortable with no key as well. I just kept it in until I could discuss it with @despiegk 

>  delete action does not make much sense I think, if we get a key and store that in the blockchain to make a reservation, the key is there forever, so it makes sense to me that we don't allow users to delete their data after a week.

I don't see the added value of delete either... @zaibon do you?

**Comment by zaibon** [comment]
Agree with everything @LeeSmet said, we've discussed it together too already.
I'll update the first comment to match these remarks
