### ISSUE TITLE
Use rivine keys for encryption 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#137]
todo:
- [ ] Document the conclusions below in the rivine documentation.

**Comment by zaibon** [comment]
I've been doing some research regarding the cryptography used in tfchaine/rivine and jumpscale.
Hear is my findings:
- tfchain/rivine uses ed25519 algorithm to sign
- the mnemonic words of a tfchain seed allow your to recover the private key
- In jumpscale they use https://github.com/pyca/pynacl/ for the cryptocgraphy, PyNACL is a library on top of libsodium.
- pynacl also uses ed25519 for signing.

Now the interesting point is that pynacl provide a method to derivate ed25519 keys to curve25519 that can then be used for encryption 
Libsodium documentation states: 
> Ed25519 keys can be converted to Curve25519 keys, so that the same key pair can be used both for authenticated encryption (crypto_box) and for signatures (crypto_sign).

https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519

Conclusion is from a singing key ed25519 we can go to any other key needed.
PrivateKey ed25519 -> Public Key: to verify signature
PrivateKey ed25519 -> Private Key curve 25519 for encryption
PrivateKey ed25519 -> Public Key curve 25519 for encryption

**Comment by LeeSmet** [comment]
The golang implementation does not have the same functionality in the standard library (conversion from ed25519 to curve25519 keys). There is however an open issue about this: https://github.com/golang/go/issues/20504. It seems no work is being done on that however.

After some more digging however, it turns out that this has been implemented as a separate library by the person who volunteered to do this in the issue, albeit it has not been merged into the standard library, see https://github.com/agl/ed25519/blob/master/extra25519/extra25519.go

**Comment by robvanmieghem** [comment]
"Curve25519  is birationally equivalent to a twisted Edwards curve used in Ed25519 signature scheme."
While I have no idea what that means, there do seem to be implementations to convert Ed25519 publicand  private keys into curve25519, I did not immediately find the reverse but I don't know if that is necessary

**Comment by zaibon** [comment]
@robvanmieghem regarding this I found some thread about that: https://github.com/jedisct1/libsodium/issues/77#issuecomment-48759936

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/rivine/commit/791ff9ca278fc941c90a829bdfccf919381c762e
