### ISSUE TITLE
Create a commercial service provider based on TF Grid by using weblet deployments

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1378]
# Create a commercial service provider business

## Purpose

To prove that the current state of the TF grid is enough to start a commercial business on.  The current TF technology stack is a good set of building blocks to create a service business on.  While proving this by doing it we also create content that explains in steps how to use the technical building blocks and put it all together into a full fledged solution.

## Outcome

- a fiat based service provider that operates well known service to a general, non technical audience (but no freebees, these are paid for services)
- a set of tutorials how to start your own service business on top of the ThreeFold technology stack.

## Initial service roadmap:

| Type              |Name           | Phase | Product description |
|:------------------|:--------------|:-:|:---- |
| *Social services *|               |   | |
|                   | Mastodon      | 1 | | 
|                   | Mattermost    | 2 | |
|                   | Discourse     | 2 | |
|                   | Peertube      | 2 | |
|                   | Wordpress     | 2 | |
|                   | Funkwhale     | 2 | |
| *Workplace*       |               |   | |
|                   | Jitsi         | 1 | #1380 | 
|                   | Taiga         | 2 | |
|                   | Gitea         | 2 | |
| *Developer*       |               |   | |
|                   | Full VM       | 1 | |
|                   | Micro VM      | 1 | |
|                   | Kubernetes    | 1 | |
|                   | Caprover      | 1 | |
|                   | Node Pilot    | 2 | |
|                   | Quantum Safe Storage | 2 | |
| *Media*       |               |   | |
|                   | Plex Media Server      | Option | |
| *Other*           |               |   | |
|                   |  Presearch    | 1 | |
|                   |  Owncloud (instant dropbox alternative)    | 1 | | 

In the table we're aiming to have only less than 10 initial services to launch with, of which 80% should be already exists today.  The focus and effort needed should be around storing the provisioning and customization information backup.

## Requirements
- fiat plus a number of leading digital currencies as payment method
- company based central provisioning wallet and tool to deploy the purchased services
- all provisioned services details (both standard details about the deployments as well as customer driven customization data) is stored and provides the possibility to do a restore when "it" fails on another 3node. 
   - This backup facility can be on storage that is provisioned with the service (and survives a service failure) or the service provider has some centralized storage (QSS) that is used to backup customer provisioning and customization data.
   - this backup facility for the configuration and customization details is part of the service charge, not separate on top of.
   - a backup facility for customer data is customer requested, provisioned and paid for (FIAT)
- aall provisioned services are monitored by a monitoring solution and service  failure will lead to service restore.  Initially this might be manual (non scalable) but we need to plan to have this done automatically based on the store configuration and customization data.  Customer data will be made available in the restored solution if customer data backup service is selected.

## Outcome
The outcome for this service provider creation is as follows:
- working service provider setup with an initial service set, to be expanded as time progresses.
- the revenues generated by this service provider business are invested in the community to support community effort to help on items like documentation optimization and creation, development of new use cases, and more to be defined.
- a (set of) manual(s) that describe in details how to start / bootstrap a service business on top of the TF grid based on the existing tool set and components
- a training material course (documentation and audio and video material) explaining how to get started  with a self owner service provider business.

##  Architecture

The problem with a FIAT (only) model is how do we create a unique identity and remember / store / create an access method to it. Few options:
- Method 1: **simple username password mechanism**: the user defines when provisioning the service.  Nothing more nothing less than any other online service
- Method 2: **generate a mnemonic**: when provisioning the service, generate the mnemonic just like with the current mastodon service and generate a unique username and password combination when the service is provisioned.  Do not let the customer choose his own (unsafe).
- Method 3: **use the TF Connect app**: this method 

Initial though is to create a wallet per individual, have them keep / remember a created mnemonic.  Very similar to what we have today for the twitter alternative (mastodon) .  That covers the "remember" who you are part, but not the pay in fiat part.

### Architecture diagram (DRAFT)

```mermaid
graph LR

subgraph Payment Provider

   paymentProcessing -->|Customer paid checked| servicePortal
end

subgraph Cloud Market
   customer[Customer] -->|Fiat payment| paymentProcessing[Payment Engine]
end 


paymentProcessing --> bank[Bank account]

subgraph TF Grid
   tfGrid[TF Grid Nodes]
   tfGridWallet[TF Grid Wallet]
end

subgraph Service Provider
   bank
   servicePortal -->|payment instruction| serviceWallet[Wallet]
   servicePortal -->|smart contract| provisioningEngine
   serviceWallet -->|Token payment| tfGridWallet
   tfGridWallet -->|Channel token payment| serviceWallet 
   provisioningEngine[Provisioning Engine]
   provisioningEngine -->|deployment instruction| tfGrid
   servicePortal -->|Account information| customer

end
```

**Comment by sasha-astiadi** [comment]
suggest add presearch, we have got a lot of leads and community members from presearch node @weynandkuijpers

**Comment by sasha-astiadi** [comment]
challenges / tbd:

- fiat payment gateway

to research:
benchmark analysis . competitors

**Comment by samtaggart** [comment]
Mik had a good point about offering an end-user storage system using QSFS, can we add that in? Probably a bigger lift but we can put it on the roadmap.

**Comment by weynandkuijpers** [comment]
> 

Done, embedded in the roadmap.

**Comment by Mik-TF** [comment]
Excellent!

In the social services section of the table, peertube is there two times. We could remove one. (I can't edit the post so I write it here.)

Another project we could add:
* provide compute+network to run APIs like the telegram bot and/or AI/ML workloads, like https://www.huggingface.co does

**Comment by scottyeager** [comment]
Some ideas and inputs :)

## Backups

Users of modern cloud services will generally operate under the assumption that data can never be lost. Furthermore, recovering from even a temporary node outage will require that all data can be reconstructed. Restoring a Gitea or Taiga instance with the users configuration but lacking all the stories and code, for example, is a total failure from the perspective of the user.

"Backups" in the cloud context usually refers to the ability to restore some previous state (whoops I deleted all my WordPress posts), rather than an ability to recover from infrastructure failures (whoops my host needed to perform a routine replacement of the single disk my data was solely stored on). Providing users with an opt in backup feature at additional cost seems likely to me to create bad user experiences if (when) they would need the backup.

The only exception I see would be the "developer" focused category, where backups would be a more complicated matter anyway (much easier to identify and target user data in a known application than an arbitrary VM).

## Example pricing analysis: Jitsi

Searching for a competitive offering in Jitsi hosting, I found that Digital Ocean offers a ["1-click" deployment](https://marketplace.digitalocean.com/apps/jitsi-server). They recommend that this runs on a CPU optimized droplet with at least 4GB of RAM, which costs $42/month (!). [Another host](https://www.webhostingzone.org/solutions/jitsi-hosting.html) offers a "Jitsi Minimal" package for $30/month with similar specs and an advertised capacity of 30 participants, as well as a couple higher level packages to accommodate more participants.

Let's compare that to Zoom's introductory paid option "Pro", where for $15/month (a bit less if paid annually) we get 100 participant capacity and 5GB of storage. With a few examples showing the cost of equivalent deployments on the Grid:

|| DO | WHZ Minimal | WHZ 70 | Zoom Pro | Grid 1 | Grid 2 | Grid 3 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Price (monthly) | $42 | $30 | $60 | $15 | ??? | ??? | ??? |
| Participants | 30 | 30 | 70  | 100 | 30 | 70 | 100+ |
| Storage (GB) | 25 | 80 | 320 | 5 | 70 | 125 | 350 |
| RAM (GB) | 4 | 4 | 8 | | 4 | 8 | 16 |
| CPU | 2 | 2 | 4 | | 2 | 4 | 8 |
| Transfer (TB) | 4 | 4 | 5 | | 4 | 5 | 8 |
| Capacity Cost | | | | | $8 | $16 | $33 |
| Transfer Cost | | | | | $6 | $7.5 | $12 |
| Total Cost | | | | | $14 | $23.50 | $45 |

The figures for the Grid are computed at 50% discount level according to the latest [pricing calculator](https://docs.google.com/spreadsheets/d/1E6MpGs15h1_flyT5AtyKp1TixH1ILuGo5tzHdmjeYdQ/), with some example data transfer allocations included. 

According to the Jitsi team, an instance accommodating 100 participants requires at least 8 cpu, 8GB of ram, and 300 mbit/s symmetric bandwidth. If that were saturated, a 1 hour meeting would consume about 270GB and 8TB of transfer allocation would last for about 30 hours of meeting per month.

Sliced another way, 1-1 chats consume at most 4mb/s up and down in 720p. That's 3.6GB per hour, and a single terrabyte of transfer ($1.5) is almost enough for four hours of 1-1 meetings five days a week. Note that bandwidth [doesn't simply scale proportionately](https://community.jitsi.org/t/bandwidth-cost-modeling/14762/10) to the number of users for larger meetings, because only the active speaker is served in full resolution.

So, while it's very difficult to compete with Zoom at the higher end of their offering (100 participants), it shouldn't be hard to offer something competitive for the average user. If some additional discount could be gained, perhaps via the sales channel or once enough demand exists to rent dedicated nodes, then the "Grid 1" example could be sold for less than Zoom Pro, say $10/month + bandwidth (probably $1 or less for most users), with a decent margin (~50%).

Oh ya, what about those backups? For a 70GB storage allocation, the cost of storage to replicate this elsewhere is also less than $1 (assuming full utilization). The backup service itself will have modest compute requirements and can serve many applications. Keeping backups is actually pretty inexpensive relative to the cost of the deployment they're backing up.

## Billing for bandwidth

Cloud providers typically offer a bundled amount of monthly bandwidth consumption (transfer) along with their VM offerings, and overages are billed at some rate. Consumer services, on the other hand, rarely have upfront limits on data transfer. Dropbox, for example, only specifies the largest file size that paid users can share with others at each tier. Github takes a more [complex](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) approach that includes a mix of some hard limits for individual files, paid options for large files, and case by case handling of large repos.

On the grid, bandwidth is metered and post billed ([all public traffic](https://github.com/threefoldtech/zos/blob/6e0fc65ef83b3a2ae8606d86c68ba5ac0a798d69/docs/architecture/decisions/0001-nu-reporting-for-priv-traffic.md)). A service provider can add up what's used by each of their customers easily by checking the consumption reports on TF Chain via GraphQL. Actually limiting a users bandwidth is probably not feasible (would need to ship the limiter along with the deployment, I think). So some options for billing:

* Included in the service offering price with no quotas or overflow, so effectively split among all users (probably good for low bandwidth applications like Taiga, definitely okay for Presearch. High users can be warned and then bumped to metered billing)
* Quota + overflow (users inevitably pay for bandwidth they don't use, but keeps things simple for those that don't overflow)
* Pass through (only pay for what's used, but billing is more complicated. Markup bandwidth cost?)

# ...

More to come, I'm sure, but that's all for now.

**Comment by weynandkuijpers** [comment]
> Another project we could add:
> 
>     * provide compute+network to run APIs like the telegram bot and/or AI/ML workloads, like https://www.huggingface.co does

What do you think warrents this a seperate category and does not make it part of "Full VM".  Do you consider this to be something that can be replicated for many things (many bots or many API's?).

**Comment by Mik-TF** [comment]
It might not need a separate category. Good point.

But I was thinking that we could offer a general service where users can try and use different kind of bots and APIs, for specific uses. So, different enterprises would propose different features. The workloads of bots and AI/ML would run on the TF Grid, via Planetary Network when possible, the scripts could be hosted on Github and/or the TF hub.  

Users could have the possibility to deploy bots that run on 3nodes.
They can write the code on the platform, it gets saved into storage on Github or the TF hub, and the compute of the bots is done by a 3node through the TF Grid.

So for example, a one-click solution to host Telegram bots. You only need to pay X$ per month, the user gives the telegram bot token, and they can run the bot. They can either write the scripts, or simple scripts/bots could be proposed. Also, we note that bots would be using AI/ML in their codes.

The bot's script can be taken from Github or the TF hub, for example, so the 3node runs the script, and if it ever fails, another 3node can simply rerun the script. This is an idea to use mostly the compute capacity, and going over the fact that we can't have "self-healing" compute as we do with QSFS and storage. The compute is centralized on only one 3node at a time. The code is stored and available on Github or TF hub.

On the AI/ML workloads side, it could be done in many ways. For example, we can host standard and mainstream AI for people to use. We can have advanced linguistic translators, text generators, question-answering bots, etc. Each enterprise would focus on one aspect or a group of related features, but all those enterprises could be based on the same basic model, for ease of expansion and development.

This might have some similarities with projects like https://colab.research.google.com/.

**Comment by Mik-TF** [comment]
How far are we from not solely hosting Wordpress, but offering the standard features of web hosting, like Bluehost does for example?

What we could offer:

* the user has its own domain, we do not provide it
* the domain is hosted via IPv4/6 addresses
* we offer a CPanel-like interface
* the user can deploy Wordpress (or others)
* users have emails, calendar
* they have a database stored on the TF Grid

**Comment by Mik-TF** [comment]
As talked with Scott, we could offer some sort of streaming solution, like [Plex](https://www.plex.tv/en-ca/). If that fits, it could be added on the list. we might need to figure out some details about how we would be doing this.

**Comment by samtaggart** [comment]
@xmonader @rkhamis Can we get some feedback on this issue to understand recommended rollout, what's done & what needs to be done, etc. Then we can create and move on an execution plan.

**Comment by Mik-TF** [comment]
<h1>TF Meeting 31-01-23</h1>

# Attendees

* Weynand
* Scott
* Sam
* Mik

# Main Content Discussed: TF Commercial Services

The meeting was very fruitful and we state here what as been talked in a point-format.
This constitutes the basic elements of the project and the overall architecture and its parameters.

* Short-term Goal
  * Take top 5 of available services
    * turn into Commercial enterprise on the TF Grid
    * start with most ready solutions
      * Mastodon
        * take basic of getmastodon.threefold.io
        * make the fiat to TFT process within the commercial entity
        * create a website with graphics (see design)
        * launch the product with affiliate links to grow
      * Taiga
      * Virtual machines
        * Full VM
        * Micro VM
      * NextCloud
        * storage
        * turn docker to flist
        * explore the product
        * generate script to deploy with characteristics form user
      * Jitsi
        * some things to settle
        * not ready as of now but great service to offer, worth to adjust what's needed
    * Possible way forward
        * we can start with Mastodon as it is mostly ready for fiat use (see getmastodon.threefold.io)
        * then, use mastodon's template for other services
          * create app, buying+deployment processes, websites, affiliate links, etc.
* Using fiat for users
  * Back-end
    * take fiat turn into TFT, deploy on the TF Grid
    * set price to be profitable before discount levels
      * take discount levels as a back-up with price fluctuations
  * Potential idea
    * Generate a vast TFT sum from investors of the commercial services
      * generate a pool to get 60% TFT discount on deployment
      * can help as a back-up if price fluctuates in bad direction too much
      * can generate more profit if price fluctuates in good direction
  * Can distribute the fiat to TFT purchase to minimize risk (TFT value fluctuation during deployment)
    * ex: 10$ per month
      * 5$ fiat to TFT
        * buy TFT 1st day of the deployment
      * 5$ fiat to TFT
        * buy TFT 15 days later
    * Result: reduce TFT value during deployment impact
    * Possibility: synchronize with TFT minting (farmers sell first week of month)
* Design of website and app
  * Goals: minimal design, simple and elegant
  * Potential inspirations: Zonaris
  * Basics: 
    * App
      * TF Connect
    * Website registration
      * getmastodon.threefold.io
  * Different possibilities
    * Simple set-up
      * Wordpress or Zola
      * AI graphics (see Kristof's utiliation for venture website)
    * Other
      * Ask past graphic contributors of TF
* Affiliate links
  * note: no paid ads, we aim at an organic growth through exponential growth affiliate link potential
  * set discounts or kickback from referrals
    * ex1: use the 5 addresses of solution provider
    * ex2: set internally (old school) affiliate program
      * adjust discounts within the company instead of using the solution provider addresses
* Story/narrative
  * What do we sell as a service? What are the advantages?
    * TF community perspective
      * we show it is possible to have fiat-based service that generate revenue stream
      * we document it for people to do it themselves
        * see Services Documentation
    * Service users
      * we offer a decentralized, safe solution
      * we offer good price for high-quality service
        * ex with Mastodon
          * plain vanilla installed
          * backup on grid (see backups)
* Services Documentation
  * we can build on what we have already
    * take documentation and organize it for specific services
      * there might be common documentation for different services
  * we can create ebooks and online websites documentation with the Threefold Documentation Builder Program (TF-DBP)
    * see the post: [Threefold Complete Documentation Project](https://forum.threefold.io/t/threefold-complete-documentation-project/3750)
      * we create all the necessary documentation in sections and parts
        * we can organize the parts into a whole (ebook, website) for specific services (with TF-DBP)
        * we can present the complete documentation
* Backups of Workloads
  * two levels of backup
    * lvl1: private backup
      * standard volume for each deployment
    * lvl2: QSFS backup of lvl1
      * quantum-safe pool facility
  * compute
    * can't lose configuration
      * saved
      * backed
      * restorable
    * data, files, links
      * backed up
