### ISSUE TITLE
Revise tokenomics 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#1412]
Until now the focus of the tokenomics was to expand the grid. Right now we need to revise them in order to put focus on utilization. 

A couple of things that already came out of the discussions: 
- Revise how CU is calculated in minting vs reservations 
- Benchmarks needed 
- Do current farmers stay on this farming policy and do we create a new farming policy for new farmers? 
- Possibility of having e.g. 10% of the possible total reward for an idle node and adding minting rewards for utilization until 100% of the node is used? 
- Adding the minimal uptime requirement again
- Making it possible for users to put their node into maintenance mode (+ notifying users who have workloads on those nodes)
- ...

**Comment by sabrinasadik** [comment]
@LeeSmet pls add to list

**Comment by LeeSmet** [comment]
- Option of giving the farmer a percentage of tokens paid for utilization instead of minting
- Revise how much is burned, to be balanced with minted
- Revise general allocation of tokens paid for contracts
- Remove minting for IP and NU, as this can just be done by awarding part of the tokens from contract cost to the farmer. Also, the minting reward for NU is currently higher than the cost, so you can get an "infinite token farm" from that
