### ISSUE TITLE
TFGrid tokenomics quick fix & better transparency

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1448]
we are working on tokenomics changes for TFGrid 4.0, but this story is about things we can do right now

## goals

- the price of the TFT should be at least 0.1 USD, its important that TF Customers perceive the value of TFT
    - we should make liquidity less important compared to price, so if not < 0.1, then is harder for people to sell
    - its in the interest of everyone to have a stable utility token
- have better reward for farmers who are willing to support the TFT
- farmers should have the rewards if they host on own node (the 50% reward for channel)
- its important to have ultimate visibility on how tokens are used and distributed
    - its in all our best interest that the TFT is safe and no-one has to doubt the intentions
    - TFT has never been pumped and dumped
    - no-one ever abused owning TFT to make himself rich, all larger collaborators have best intention
    - lets make this great TFT feature visible to everyone

## changes

- all new 3nodes get default lockup to 0.1USD per TFT (we don't touch existing ones)
    - remark: DAO can always loosen this param if this would be required
    - existing farmers can opt in to the same approach
- 50% + 10% of utilization goes to the farmers who locked up their tokens
    - also the utilisation earned tokens are locked at 0.1
- everyone who wants can lock their accounts as well just to show their support (also at 0.1)
- we remove solution providers, its giving us too much headache
- if farmers deploy on their own nodes then the 50% utilization fee is given to them 
- we show the token distribution in clear way also on website, so people know where tokens are and who is selling
    - we show history
- we have a SQLITEDB which has all transactions till date (from both blockchains: rivine, stellar, binance?)
    - known accounts in table
    - accounts with positions (just simple = amount of TFT)
    - accounts with all transactions (from to who and when and how much)

**Comment by robvanmieghem** [comment]
Scripts to put preconversion rivine balances and accounts, all minted tokens and tfta       destructions ina sqlite db: https://github.com/threefoldfoundation/tft-stellar/tree/master/scripts/analysis

**Comment by robvanmieghem** [comment]
The folder contains an extra script to add the Stellar addresses to the rivine table now ( explained in the readme)

**Comment by despiegk** [comment]
# OPTION 1

we implement for all farmers what we had already suggested before this is the locked for 2 years or 30% utilization

if we do this then its for all farmers

# OPTION 2

the 0.1 USD per TFT lockup, believe its better because we can get more people to lockup compared to just new farmers

> we need to come to conclusion asap, lets see how to do GEP, ... and talk about it with community

**Comment by xmonader** [comment]
@renauter please check this and check with Rob if you need more clarifications

**Comment by robvanmieghem** [comment]
Technically, let's not overcomplicate it. 
Yes, we could make all kinds of difficult constructions with Escrow accounts, Stellar-tfchain cross chain rules and authorizations and all kinds of things.
We can also just record the amount due to who with a farming proof hash and a date of creation (yes, like plain records in a table) in tfchain and that's it. 
Tfchain has all other info ( like USD price, Stellar addresses,..) too and if we do on-chain minting or move away from Stellar, or the rules change,... there is no problem.

**Comment by robvanmieghem** [comment]
@sabrinasadik assigned you too for Kristof's remark
> we need to come to conclusion asap, lets see how to do GEP, ... and talk about it with community

**Comment by robvanmieghem** [comment]
Regarding the analysis of TFT transactions, https://github.com/threefoldfoundation/tft-stellar/tree/master/scripts/analysis now also contains a script to have all rivine transactions in the db and a go program in the stellar folder to add all payments on the stellar network and additions to and withdrawals from liquidity pools.
Trades are still to be indexed.

**Comment by robvanmieghem** [comment]
I don't think having the current balance is needed as this only requires 1 single request to horizon

**Comment by scottyeager** [comment]
Request for comment on this matter at forum here: https://forum.threefold.io/t/start-farming-reward-lock-and-utilization-payments-to-farmers/4069

**Comment by renauter** [comment]
Some update around tokenomics from the forum topic https://forum.threefold.io/t/start-farming-reward-lock-and-utilization-payments-to-farmers/4069

Seems there is some consensus around the following proposition

- TFT farming lock
  For each node on TFGrid: 
  * 2 years lock since node registered (unique fixed lock, i.e. after 2 years all TFT farmed are unlocked) 
  * or after 30% utilization for 3 months (i.e. at least one active contract older than 3 months on a node that rents at least 30% of its capacity)
- Remove solution provider program
- Distribute 50% to farmer running the workloads
- TFT farming rewards price set to 0.10 instead of the current 0.08

Question now is are we OK to submit this proposal to farmers approval via DAO voting?
Or we wait a bit to give time for other alternatives?

**Comment by Mik-TF** [comment]
I think we can give some more time, and also give more info on the forum post concerning @despiegk's arguments for lock at 10 cents. I think it's stated clearly here, but might not have been as well presented in the forum post.

**Comment by Mik-TF** [comment]
So I tried to get some feedback on the 10 cents locking option [here](https://forum.threefold.io/t/start-farming-reward-lock-and-utilization-payments-to-farmers/4069/61). Seems we do have a consensus for the 30% utilization, 2 years lock (option 1 as in this github issue), as stated clearly by @renauter [here](https://github.com/threefoldtech/home/issues/1448#issuecomment-1737268573) in this thread.

I think we should make sure we agree with this then make a vote on the DAO.

I will once again ask the same question as Renaud: are we OK to submit this proposal to farmers approval via DAO voting?

If yes, we could proceed sooner than later.

**Comment by Mik-TF** [comment]
If we think some members won't speak their mind on the forum but might think otherwise than the general consensus, I propose to have a 3 options vote for the DAO. Otherwise, we are building a dao vote based on a few people discussing on the forum. With this 3 options vote, we would have a real sense of the members' opinions.

* Option 0
  * no change
* Option 1
  - TFT farming lock
    - For each node on TFGrid: 
      * 2 years lock since node registered (unique fixed lock, i.e. after 2 years all TFT farmed are unlocked) 
      * or after 30% utilization for 3 months (i.e. at least one active contract older than 3 months on a node that rents at least 30% of its capacity)
  - Remove solution provider program
  - Distribute 50% of utilization rewards to farmer running the workloads
  - TFT farming rewards price set to 0.10 instead of the current 0.08
* Option 2
  - TFT farming lock
    - Lock until TFT reaches 10 cents
  - Remove solution provider program
  - Distribute 50% of utilization rewards to farmer running the workloads
  - TFT farming rewards price set to 0.10 instead of the current 0.08

**Comment by xmonader** [comment]
@renauter can we update with what we discussed tonight?

**Comment by renauter** [comment]
After we discussed we came to conclusion that we still don't have consensus so we postpone it for 3.13.
Due to the potential impact (some farmers may leave the grid), each introduced rule (such as tokens locking / solution provider removal / ... ) need to be better matured with community before being submitted (independently?) to a DAO proposal for farmers to vote for.

Also some new concept around "cooperation" of farmers was proposed (ability for farmers to gather and encourage traction for capacity utilization that would accelerate the tokens unlocking).

Then we talked about how do we technically do the tokens locking. Since TFT are minted in stellar, would we store the amount locked on chain initially before they are unlocked ? @despiegk seems to have an idea and will come back to us

**Comment by despiegk** [comment]
maybe not true, we got some push back from some farmers who still want to see it in 3.12
lets see how we can do it

**Comment by renauter** [comment]
Since no consensus yet, new post was created on forum for a second round of ideas/proposals https://forum.threefold.io/t/token-lock-recap-and-next-steps/4104

**Comment by Mik-TF** [comment]
We could proceed as such:

* Let people discuss on the two options on the second round post (see @renauter reply above)
* Have an anonymous poll on the TF forum about the two options
* Make a DAO vote on the most popular option from the poll
* If the DAO vote is "no", we could then have another DAO vote for the 2nd option. If this 2nd DAO vote is also no, we do not lock tokens.

**Comment by despiegk** [comment]
a lot has been achieved so far, we can close for now and continue on other story
