### ISSUE TITLE
Second time problem with a bridge

### ISSUE THREAD

**Issue by Zachem11** [threefoldtech/home#1498]
It`s sad to say, but in BSC-TFT bridge my funds stacked. Second time :-<
Сhecked with guide, memo entered correctly
https://stellar.expert/explorer/public/tx/a9f8042e84d1fe4387c4bc3a5dc8823cc5bc3e520b57047f12048b516754dd98
Sent from TFT to BSC
What unlucky man i am...

**Comment by coesensbert** [comment]
Unfortunate coincidence it happened to you a second time, our apologies. Could you check you received your bridged funds @Zachem11 ?

Some context: BSC is very (very) hard to maintain, it requires constant [full node upgrades](https://github.com/bnb-chain/bsc/releases). This time we need to re-download all chain data because BSC is switching to PBSS + PebbleDB (and this BEFORE the Kepler hard fork .. jep .. another hard fork) . One such snapshot is ~2TB which needs to be downloaded and extracted 4 times .. time consuming. We are also removing the light client (which created lots of instabilities) from the bsc bridge, this means for now we can only connect to one BSC full node at the time. This specific full node was in trouble, hence our bridge could not fetch newest blocks. On top of that we need to prune BSC nodes very regularly to avoid that the used space goes from 2TB to 5TB and more .. If the one the bridge is using needs to be pruned, we first need to config the bridge to use another one .. etc.

**Comment by Zachem11** [comment]
Кeceived it, I’m very glad, this time you really helped very quickly, thank you very much.

I saw on Github that you are working on a bridge to the Polygon network, I hope at least it won’t torment you so much
In general, I have known your project for less than a month, and it surprises with its depth and level of support from the developers. Good luck to you and I hope I don't have to bother you anymore.

P.S If you still have to, in which repository is it better to do this, otherwise I’m not entirely sure that this one is suitable

Sincerely

**Comment by Zachem11** [comment]
Problem is solved
