### ISSUE TITLE
coredns not clear

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#154]
![image](https://user-images.githubusercontent.com/6021844/54866919-ca7c3f80-4d7a-11e9-8bf6-e70cae67ffe2.png)

why fork from non original repo
how do we know what got changed on this repo?
how do we keep it up to date?

**Comment by zaibon** [comment]
So the reason we fork CoreDNS was because they didn't support to connect to ETCD that was password protected. 
So we did implement this on our fork: https://github.com/threefoldtech/coredns/commit/8feb641500ffa726847ddada677f7debf05519c9

Our [CoreDNS template](https://github.com/threefoldtech/0-templates/tree/development/templates/coredns) and [SAL](https://github.com/threefoldtech/jumpscale_lib/tree/development/JumpscaleLib/sal_zos/coredns) uses an flist build from this repository.

Since then I re-implemented our fix in a cleaner way and propose it uptream: https://github.com/coredns/coredns/pull/2442
My patch has been merge already. 
What left to be done is to modify our code to deal with the version from uptream again. 
Once this is done we can get rid of our fork since it won't contain anything specific for us anymore.
