### ISSUE TITLE
Community Registration v10.1.0 [development_community]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#407]
This story card addresses the tooling needed to onboard a 3bot user to our community seamlessly.

### 
- [x] login with 3bot
- [x] get 3bot user name and email
- [x] possibility to get referral code through get statement in the invitation url
- [x] support for admin invitations
- [x] if no referral code is sent in the request, possibility to enter inviting 3bot name
- [x] load FFP spaces into the chatflow 
- [x] remember which spaces the user is interested in
- [x] if user is not on FFP, register the user there
- [x] subscribe the user to the spaces they're interested in
- [x] markdown support for dynamic macro
    - [x] welcome message
    - [x] nice threefold logo
    - [x] shows spaces with latest posts
    - [x] referral impact tree, showing who got invited by this user and how much they impacted
 - [ ] session management

### current usage:

to join FFP, inviation could look like :
```
https://142.93.189.88/chat/session/community_join?referral=28812ede6c4e424eba740b3bf74fa73b
```
if you are admin join this to get your referral code and continue in process

![image](https://user-images.githubusercontent.com/10259267/69244362-7fd2f180-0bad-11ea-8ae9-93a0df741c1b.png)

**Comment by BolaNasr** [comment]
First of all should login with **3bot login** 

First to join our FFP should invited by someone Like :
```
https://142.93.189.88/chat/session/community_join?referral=9f58d45c187d4570bf9d3d601159e22d
```
if this referral code is not correct will ask you about the 3bot name if correct can continue :
1- get all spaces in FFP staging
2- can join what's selected ( if you have account or not) because it's create account automatic at FFP
3- then can goto your wiki page with your spaces and latest posts 
4- can see your tree about invited pepole 

if you are admin join this to get your referral code and continue in process
```
https://142.93.189.88/chat/session/community_join_master
```

**Comment by gmachtel** [comment]
Depending on branch development_actorsimprovement stable

**Comment by despiegk** [comment]
lets redefine story
