### ISSUE TITLE
As a user, reserve capacity - add payment flow 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#410]
Extension of 

**More info**
Part of the [Container Deployment flow](https://docs.google.com/drawings/d/1KoBF_cYLPE5YoFM85bxsWEl_RlJEoA16pMlFUZDPhSk/edit?usp=sharing)
[Process flow](https://github.com/threefoldtech/tf_cockpit/blob/master/specs/architecture/ProcessFlow.md)

Before implementation; please add to this issue:
- Actor in and outputs
- How does this request from the node end up in the cockpit; what is the technical flow

**Mockups**

Based on :

Payment to be initiated. first calculation: 

then pay:

**DOD**
- Actors are working and tested
- UI is linked to actors
- Node or nodes chosen (after search based on available capacity, location, certified capacity Y/N)
- Capacity chosen for nodes (CRU, MRU, HRU, SRU) 
- Reservation duration chosen
- Wireguard configuration filled
- Result of action is 'capacity reservation pending with farmer to be signed'
- On join notification is received both with consumer and farmer

**Open questions**
- Pay before confirmation by farmer ? If direct payment and farmer refuses, refund needed. Other possibility: lock the funds.

**Comment by zaibon** [comment]
> Ok so that is a centralized phonebook only we can populate

As of now we are the only one using the API of the phonebook actor yes. But it has been design so anyone could use it. I don't think there is any restriction since all information in there are public.

You can check the actor : https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/phonebook/actors/phonebook.py
