### ISSUE TITLE
new test framework for jumpscale [development_testframework]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#425]
## goal

come up with right strategy how we will do our tests using our own TFGrid

## requirements

- [ ] keep it super simple
- [ ] tests are human readable (no complex code) and use our DSL's as much as possible
- [ ] can run interactively as part of j...  needs to be super easy for everyone to use
- [ ] serves as example code
- [ ] uses TFGrid
- [ ] uses myjobs & scheduling feature of actors

## ideas

see input in threefoldtech/jumpscaleX_core#190 also in #418

**Comment by john-kheir** [comment]
1- I think those steps written above : 
 - uses TFGrid
 - uses myjobs & scheduling feature of actors

are part of this story: https://github.com/threefoldtech/home/issues/420

2- Unittest comes with python out of the box, so we can just try to use it and make it run interactively as part of j, so that we can have all the features https://github.com/threefoldtech/jumpscaleX_core/issues/190 used by unittest and at the same time wrap it with `j` .. My question here is that enough for this story?

**Comment by xmonader** [comment]
closed will be replaced with a new issue
