### ISSUE TITLE
As a mobile user, go straight to your app on login attempt

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#434]
When clicking "login with 3bot" on any web-application, there is no need for mobile users to enter there name first, they should be redirected to either app/play store or the app itself to login.

Currently the user is presented with this screen when attempting to authenticate with any web-application on mobile:

![image](https://user-images.githubusercontent.com/7256303/70450003-418d6b80-1aa3-11ea-8c61-50f9e9a16846.png)

Most people won't receive this pop-op and will simply be redirect to the next screen. This is due to the fact that I have production, staging and local installed on my device.

![image](https://user-images.githubusercontent.com/7256303/70450073-5e29a380-1aa3-11ea-939f-d3c72fbc1d46.png)

![image](https://user-images.githubusercontent.com/7256303/70450080-6255c100-1aa3-11ea-8b49-734936dba528.png)

- [x] Users that are redirected and **do have an account** that is registered should be presented with the login attempt instantly. 

- [x] Users that are redirected to the app and **don't have an account** yet should be presented with the registration flow. (If possible, finish the login attempt after they signed up)

- [ ] If they **don't have the app installed** they should be redirected to the corresponding store to download it.

**Comment by DylanVerstraete** [comment]
This is harder than it looks. Since the device cannot give information to the frontend about the doublename. When the user wants to log in on a mobile device we want to show a popup that takes him to the app. At that point in the frontend we cannot send a socket message that the user want to log in (since we dont have the double name). This means we have to send this 'login' message from the mobile app when the user opens it.
 
I tried using sockets in the mobile app, but flutter support for sockets is weak and I cannot get this working.

Proposal. 
- Remove the login api socket endpoint and replace it with a http post endpoint.
- Call the login api endpoint from the app when the user get a prompt to open it.
- Refactor the way the frontend called this 'login' socket endpoint

**Comment by jdelrue** [comment]
Right now we are working with double name to correlate the data, this is causing the issue.

If we use a random correlation ID, generated in the frontend. Send this correlation ID to the app, use the ID to get the login attempt we can notify the frontend when login is passed. This should fix the issue I think?

**Comment by DylanVerstraete** [comment]
It's not needed to change how we correlate the data. Since the proposals above take into account this correlation. The login attempt right now is based on 'doubleName' and 'sid', these things we can also get from the app.

Changing it to a random correlation ID will be a lot of refactoring.

**Comment by DylanVerstraete** [comment]
@MathiasDeWeerdt What are your thoughts on this ?

**Comment by DylanVerstraete** [comment]
First Work in progress of : `Users that are redirected and do have an account that is registered should be presented with the login attempt instantly.` has been committed. This should be tested on android aswel. Please let me know if bugs occur

**Comment by DylanVerstraete** [comment]
Completion of : `Users that are redirected to the app and don't have an account yet should be presented with the registration flow. (If possible, finish the login attempt after they signed up)` has been committed. This should be tested on android aswel. Please let me know if bugs occur

**Comment by DylanVerstraete** [comment]
I cannot find a solution for `If they don't have the app installed they should be redirected to the corresponding store to download it.` Maybe @MathiasDeWeerdt can help me out with this.

**Comment by jdelrue** [comment]
@coeneivan can you take this up on monday
