### ISSUE TITLE
basic test for JSX 10.2 using scheduling/myjobs [development_testtool]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#481]
- [x] create j.tools.tester tool
- [x] create specs (define the class)
- [ ] create tests dir in there, to test e.g the scheduler
    - [ ] check working of the scheduler
- [ ] create a class with all tests we want to run for base JSX 10.2
    - [x] method per test
    - [ ] use j.servers.myjobs.schedule if something blocking or needs to be pushed to backend
- [ ] then call the methods using the scheduler so we get parallelisation
- [ ] use self._log methods
- [ ] create log handler which will capture the logs onto a readable file

## j.tools.tester

```python
tester = j.tools.tester.get()
tester.start()
```
## some scenario's

- use containers (JSX), can have more than 1

## requirements

- easy to adjust
- < 30 min on OSX machine

**Comment by BolaNasr** [comment]
i working on this PR https://github.com/threefoldtech/jumpscaleX_core/pull/382
but for sure i have more problem in this tools because it doesn't make sense test JSX using JSX 
for example:
- we using in our test Tmux ( on starting tmux testing , it closes all panes ) and break our tools
- in our testing Tools we are using BCDB to save models of jobs but when (BCDB test starting , it clear all BCDB ) and our tools doesn't found model id  

and so on

**Comment by xmonader** [comment]
closed will be replaced with a new issue
