### ISSUE TITLE
3bot communication [development_gedis_authentication]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#523]
allow 3bots to communicate to each other

story to be further defined

## linked 

- [ ] threefoldtech/jumpscaleX_core#326
- [ ] threefoldtech/jumpscaleX_core#375
- [x] [Allow to create container with public IPv6](https://github.com/threefoldtech/zos/pull/515)

**Comment by zaibon** [comment]
I'll try to summarize the current status and possible solution for this.

**Facts** :
- 3Bot runs in containers on 0-OS node.
- All 3Bots should be able to "talk" to each other
- on 0-OS, a container MUST be part of a network. The network is defined by its owner.
- 3Bot should be reachable using DNS e.g: `zaibon.3bot.grid.tf` should point to the 3bot of user `zaibon`
- a 3Bot server should be own and managed by its owner only. TF should never be in the middle.

The original design for this was to register all 3Bot server in the TFGateway. So all traffic between 3bot would go over the "public" internet and be routed between bots through the TFGateways.
Here is the problems if we go that path:
- TFGateway currently only support HTTP, which mean the 3bot won't be able to communicate using Gedis, but will have to use the gedis to HTTP layer. Defeating a bit the purpose of Gedis in the first place.
- This architecture is not p2p at all since it always requires the Gateway to proxy all the traffic
- Gedis to HTTP layer makes the HTTP request very strange looking cause it is 100% generated and we cannot really leverage any HTTP protocol features

I think before we go forward here we should answer some questions:
- Which protocol do we want to use for inter 3bot communication
- What minimum performance do we want to have for inter 3bot communication
- How much development work can we allocate for this since we are a bit under a time constraint

**Comment by xmonader** [comment]
> TFGateway currently only support HTTP, which mean the 3bot won't be able to communicate using Gedis, but will have to use the gedis to HTTP layer. Defeating a bit the purpose of Gedis in the first place.

@zaibon Hmm, but nothing prevents forwarding 443 to local redis (running on tls using stunnel for example)

I ran stunnel/redis proxy and forwarded connections on tcprouter `ahmed-redis.bots.com:443` to stunnel/redis proxy backend service and used the redis client and it all worked out


![image](https://user-images.githubusercontent.com/64129/73686363-7ea36200-46d0-11ea-9914-b5fb5e64e973.png)

**Comment by zaibon** [comment]
Ha, so TCP/TLS is supported by our TCP router, this is plain TCP that is not. Good to know.

**Comment by muhamadazmy** [comment]
May be we should thing differently about this issue. If we need the 3bot to communicate we don't have to make them able to reach each other, but instead introduce a public messaging service. the way we have bcdb for grid nodes. 

All 3bot already has access to the internet, we can have another bcdb running centralized, and then 3bots can push messages to other nodes via bcdb, and answers can be done the same way (push a result to a message)

Of course this totally depend on the kinds of communication that is required 3bot. This definitely won't work to stream data for example.

Of course the bad side is that we now have to introduce another central point of failure :/ hence i don't fully like this solution, but i thought i leave it here just in case.

**Comment by zaibon** [comment]
@muhamadazmy this is not an option no. Direct communication between 3bot is mandatory.

**Comment by zaibon** [comment]
Ok so I think we have found a working solution. I wasn't right when I said that 0-OS doesn't allow any public networking for container. We actually already provide this feature for 0-DB. 0-DB are only exposed over IPv6.

Which means we can use the same kind of construct to give a public IPv6 address to all the 3bot container. The result is all these container have a dual stack ipv4/ipv6 with one leg into the private overlay network of the user and one on the public internet over IPv6.

The code change in 0-OS are trivial (almost done already).

With this setup. All 3bots can communicate directly in a P2P manner over ipv6.
For "normal" access of the 3bot Web UI. The TGGateway (DNS/HTTP proxy) can still be used so people that doesn't have an IPv6 enabled device can still reach their 3bot.

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/home/issues/587
