### ISSUE TITLE
codeserver for jumpscale

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#538]
threebot user should be able to start a development environment in their browser. use [codeserver](https://github.com/cdr/code-server)

# goal 
allow any own developer to collaborate with anyone else in super easy way on 3bot code, this usecase will serve as an example

## checklist
- [x] create a builder for codeserver threefoldtech/jumpscaleX_builders/issues/55
- [x] create image with jumpscale and codeserver
- [x] create package to start/stop expose codeserver

**Comment by ranatrk** [comment]
Gitpod always starts the container with the user `gitpod` and that cannot be changed, there were multiple issues opened for that but there is no news regarding the update of that anytime soon
Approaches investigated:
- Install jumpscale by adding commands in the `.gitpod.yml` file:
   This approach failed as there is no access to root at all and so jumpscale cannot be installed in the container
- Install jumpscale by adding commands in `.gitpod.DockerFile` :
   - running the commands to start docker with root before the gitpod user is created and used, this failed as the gitpod user wont have access to /sandbox
   - installing jumpscale with root, then changing the owner of sandbox to gitpod and allow read/write/exec access to root. Then the user gitpod can start kosmos. This failed because even though gitpod user can start kosmos but cannot build or do anything that requirs root user such as apt-get update or installations

Currently still investigating other possible approaches

**Comment by ranatrk** [comment]
Current approach being investigated: adding gitpod user to sudoers and install jumpscale with root

**Comment by xmonader** [comment]
Moving this to blocked as gitpod doesn't allow root/sudoers at run time 

https://github.com/gitpod-io/gitpod/issues/39
https://github.com/gitpod-io/gitpod/issues/755

possible solutions: 
- rewriting jumpscale installer to not require root,  have all of its deps included in the image and having no need for "apt calls" or anything that requires super access
- merging [theia-IDE ](https://theia-ide.org)with threebot flist and spawning containers directly from that (probably the best)

**Comment by ranatrk** [comment]
> Maybe they are allowing sudo in runtime now @ranatrk ?
> 
No not yet , the problem with sudo was fixed by adding th user to sudoers but still there are other issues in installation of jumpscale on their environment

**Comment by ranatrk** [comment]
Image created using a [Dockerfile](https://github.com/threefoldfoundation/token_simulator/blob/master/Dockerfile) which contains jumpscale installed, and the binaries of [code-server](https://github.com/cdr/code-server) added.
https://hub.docker.com/repository/docker/ranatrk/jumpscale_codeserver

**Comment by ranatrk** [comment]
- Created package to start and stop code server by adding the package
https://github.com/threefoldtech/jumpscaleX_threebot/commit/d4d0169a4721aa9b9af624898833efa75f6ec16d
- Codeserver starts with user root and so the user has the freedom to develop on the container and can view any directory or workspace they want
- The environment is accessible through `HOST/codeserver`
-Screenshot of the environment with `/sandbox` directory opened and `kosmos`  started in the terminal:
![Screenshot from 2020-02-17 15-46-37](https://user-images.githubusercontent.com/17128393/74659352-d647d000-519c-11ea-9dbe-31b0f7c2fcba.png)

**Comment by xmonader** [comment]
I splitted the simulator part into another story https://github.com/threefoldtech/home/issues/537

**Comment by Dina-Abd-Elrahman** [comment]
- I just downloaded the docker image but the i cannot access code-server and also the jsx doesn't started by default.

**Comment by ranatrk** [comment]
The codeserver will be available from the admin panel, so only the package and builder are needed. The image was created as an extra option but is not required.

**Comment by Dina-Abd-Elrahman** [comment]
- we can close this issue now.
