### ISSUE TITLE
Create docker image for ubuntu 19.10 [unstable_docker1910]

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/home#562]
In our JSX install container-install
Start from development_baseclasses !!! brach (needs to move to unstable)

Note: will upgrade to ubuntu 20.04 in 1 month

Use 
- jsx basebuilder
- jsx threebotbuilder

Use a strong machine e.g. on internet (digital ocean) and use the syncer in jumpscale

j.clients.ssh.$name.syncer…
Monitoring is broken, but rsync werkt (let's check monitoring)

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/pull/606/files

**Comment by ashraffouda** [comment]
I created a new phusion image based on ubuntu 19.10 and pushed it to threefoldtech/phusion:19.10 
also pushed a new image for threefoldtech/3bot:19.10 based on that image
for the syncer monitoring,  events from watchdog were timing out silently because we have too many files to watch  which cause nothing to be triggered when something change and it is now fixed also

**Comment by rkhamis** [comment]
done and verified
