### ISSUE TITLE
Wizard Flist Deployment [development_wizardflist]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#584]
While we are attempting to deploy flists / containers / expose certain ports on the grid we encountered the following issues:

The following issues are blocking.
- [x] https://github.com/threefoldtech/zos/issues/815
- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/870
- [ ] https://github.com/threefoldtech/jumpscaleX_core/issues/892
- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/893

New issues:
- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/896

**Comment by jdelrue** [comment]
Has to be checked with @zaibon

**Comment by jdelrue** [comment]
on Monday @MathiasDeWeerdt can start using the docs of TF to deploy FFC on the grid

**Comment by MathiasDeWeerdt** [comment]
> on Monday @MathiasDeWeerdt can start using the docs of TF to deploy FFC on the grid

Reported my findings.

**Comment by zaibon** [comment]
> threefoldtech/zos#775
 threefoldtech/jumpscaleX_threebot#691

These two issue are being investigated. But they should not be blocking cause they only happen sometimes. Retrying is a valid option when hitting those.

>  threefoldtech/jumpscaleX_threebot#689 

Some extra detail has been asked for this one. 

> During the creation of a ubuntu container I am never presented with the option to select storage. And by default I receive 250Mb which isn't usable.

The problem here is you are trying to install your solution on top of a container. This is not how a containerized application works. In a container world your container image (flist) contains all your application data. With 0-OS it it the same. Any file coming from the flist is not taken in account in the storage quota. So build a proper flist and start a container using it. 

if you really need disk access with more storage, then just attach a volume to your container.

>  Unable to edit a flist or container after I have purchased. I would like add more cores, ram, storage ..

This is not supported yet. Container cannot be modified at runtime (here we are similar to docker). If you need to modify something in your container, stop it and create a new one.

**Comment by MathiasDeWeerdt** [comment]
Updated the issue.

**Comment by MathiasDeWeerdt** [comment]
Busy re-reviewing all the issues.
