### ISSUE TITLE
Update farmer public address when wallet moves from TFChain to Stellar

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#631]
Converting wallet from TFChain to Stellar keeps the private keys but public address is different. 
So the public address of the farmer in the explorer must also be updated.

**Comment by zaibon** [comment]
I propose that we do NOT get involved in this or try to automate any of this.
The farmer can already update their farm information. This include add/remove wallet address.

Plus, once payment is enabled, the farm MUST have a valid TFT stellar address configured otherwise no reservation will be able to be made for their node. So they will do it anyhow by themselves. No point getting us involved here.

As long as all the tooling for the farmer works of course.
