### ISSUE TITLE
Investigate explorer HA options

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#67]
todo: 1d
- [x] Check with Jan
- [ ] list further options

**Comment by delandtj** [comment]
The Explorer machines crash sometimes. A part from the fact that we need to find out __why__ they crash and have that fixed either way, we will still encounter explorer nodes to go belly-up just because the hardware fails.

We have several things in place already (the gateway templates and DNS) that we can leverage:

Set up a cluster where we have 2-3 Explorer nodes that catch up on the blockchain. These nodes are running stand-alone and as back-end for the 2 gateway nodes, of which one can fail. in both Gateway nodes, the Traefik daemon is configured to proxy sticky sessions to the Eplorer node(s)

eventually we can also add a monitor to the Traefiks, and update CoreDns to use only one Traefik in case one fails.

That would be as HA as possible with the tools we have now.

**Comment by robvanmieghem** [comment]
follow up issue: https://github.com/threefoldtech/home/issues/71

**Comment by robvanmieghem** [comment]
Other options with multiple explorers are more difficult since it can not be ensured they do are not out of sync since they do not share a common datastore.We also do not have the distributed grid in place yet and cloudflare is no option either since we don't want to hand over the dnsmanagement to yet another place.
