### ISSUE TITLE
GE: deployment fails

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#705]
tried a new network: 9477 OK 
ubuntu: 9479 OK

k8s: 9480 failed
Sorry your reservation 9480 failed to deploy in time:

**Comment by zaibon** [comment]
I had a look at the reservation 9480. Like the error says the provisioning of the workloads was not done in time. 
Digging the detail of the reservation it seems this node `HugtVL51BFNLbZbbxnWu2GEe8hV97YVPac19zy5wwNpT` is not in good shape and it not processing reservation at the moment.

From the debug log I see there is an issue with the network configuration of this node: `fatal failed to create DMZ error="ndmz: could not node create pub iface 6: failed to find a valid network interface to use as parent for ndmz public interface: no interface found with ipv6"` Seems some tweaking of the farm router is required.

This network health for node is not yet reported, so that would have been hard to detect. But this is an known issue that is nearly solved. You can follow progress at
https://github.com/threefoldtech/jumpscaleX_threebot/pull/690
https://github.com/threefoldtech/tfexplorer/issues/61

**Comment by zaibon** [comment]
Closing for now since it seems this is a farm configuration issue. Feel free to re-open if this still happens once the selected nodes are all healthy
