### ISSUE TITLE
GE: Nodes has No Interfaces 

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/home#736]
In our Salzburg Farm we have 5 Nodes that did not get a IPv6 Interface.
1x Dl 385

12775 | BSusuRh6qFzheQFwNPe1S5FA5pdSZVJwVLhpNS6GN4XD | GreenEdgeAustria-Salzburg1 | no int

And 4x Apollo 4510

12775 | HugtVL51BFNLbZbbxnWu2GEe8hV97YVPac19zy5wwNpT | GreenEdgeAustria-Salzburg1 | no int
12775 | 9KAbX21NGbZYupBJ6EeeWx3ZTKDx7ADevr8qtmEa5WkC | GreenEdgeAustria-Salzburg1 | no int
12775 | 9kcLeTuseybGHGWw2YXvdu4kk2jZzyZCaCHV9t6Axqqx | GreenEdgeAustria-Salzburg1 | no int
12775 | 3h4TKp11bNWjb2UemgrVwayuPnYcs2M1bccXvi3jPR2Y | GreenEdgeAustria-Salzburg1 | no int

During Boot the ZOs fails to configure the Network

![image](https://user-images.githubusercontent.com/39131062/82668075-4d2bb380-9c39-11ea-998f-609b1192acbf.png)

Restart did not change the issue

**Comment by zaibon** [comment]
These nodes indeed are failing to receive a proper network configuration. Seems the problem comes from the router of the farm that doesn't gives an valid ipv6 address to the node which prevent from properly starting its network daemon. 
Error is `ndmz: could not node create pub iface 6: failed to find a valid network interface to use as parent for ndmz public interface: no interface found with ipv6`

Regarding the empty interfaces detail, this was a bug recently introduced and already fix at https://github.com/threefoldtech/zos/commit/b6082a7934e2cbd877528db7daa7a52835d7b1f6.
The fix will be available once 0.3.2 is deployed on mainnet.

**Comment by joefoxton** [comment]
@gneumann333 Sounds like this can be closed.
