### ISSUE TITLE
solution flists

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#777]
add Dockerfile,  zinit, any scripts for building the docker image + flists used in our grid solutions and make sure to have README.md file describing the building, conversion and usage.

use: https://github.com/threefoldtech/tf-images

until we figure out if we want to merge with https://github.com/threefoldtech/apps or the other way around.

**Comment by muhamadazmy** [comment]
@rkhamis I created a repo that create 2 base images
- alpine 
- ubuntu 
but the difference is, they use zinit as process manger, it's way reliable than a start.sh script because it has built in restart for the services if they fail. Also you can configure multiple services to start with dependency (set an order).
The base images also have buit in ssh, and also accept SSH_KEY env where u can pass your public ssh key. to get access to the container.

Adding a service is very easy, you pick the base, and just put your binaries plus your zinit unit (yaml) config to auto start the service. You leave the entrypoint empty because the flist is configured to start zinit.

Already some flists that uses those base images are)
- Prometheus 
- Minio
- Redis

**Comment by rkhamis** [comment]
thanks @muhamadazmy

I'll change the description

**Comment by xmonader** [comment]
@muhamadazmy @rkhamis this https://github.com/threefoldtech/apps should be unified with https://github.com/threefoldtech/tf-images

**Comment by sasha-astiadi** [comment]
@rkhamis is this issue still valid for december / future?
