### ISSUE TITLE
Host the most recent version of OroCRM

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#863]
- [x] Set up email
- [x] Set up DNS
- [x] Edit configuration to be able to create docker image
- [x] Convert mysql to mariadb
- [x] Set up SSL certificates
- [x] Create docker image
- [x] Host docker image
- [x] Fix reverse proxy websocket ( UX improvement )
- [ ] Clean docker image to not contain any secrets ( optional )
- [ ] Backup system with Google Cloud 
- [ ] CI/CD on gitlab ( optional )

**Comment by xmonader** [comment]
please address the following

- fork repo link
- why use google cloud for backup? we should use s3
- ssl certificates should be done automatically using certbot + nginx or the webserver needed (not manual)
- ci/cd why bother with gitlab?

**Comment by MathiasDeWeerdt** [comment]
> * fork repo link
Currenty we dont have repo yet, I will make one today.

> * why use google cloud for backup? we should use s3
I didn't know this, we use google cloud backup internally at Jimber.

> * ssl certificates should be done automatically using certbot + nginx or the webserver needed (not manual)
We had to create a reverse proxy to talk to the oroCRM docker, this is done with nginx and certbot. Some manual config was needed to configure php and websocket redirection. In combination with using the latest php and nginx, which seemed to be hopelessly outdated in the oroCRM documentation. 

> * ci/cd why bother with gitlab?
Because that is what we use internally, this hasn't been done yet.

> * dockerfile should live in https://github.com/threefoldtech/tf-images repo
Docker file is created from scratch since the Dockerfile from them doesn't exist, only from 3 years ago which isn't updated.
I will upload it to the repo provided.
