### ISSUE TITLE
capacity pools for nodes which got removed

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#893]
I think there is something wrong if nodes get removed from capacity pool,
the capacity pool seems to be not intact

I booted a new node

I added a new capacity pool
then I could deploy a workload, before did not work

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/93347742-b7461500-f835-11ea-97ac-f45adb1611a1.png)

howcome it still says 5 nodes, the nodes are gone and a new one added

**Comment by m-motawea** [comment]
pools are bound to the node_ids of the farm when it was created not the farm itself. that's why they are not auto updated when a node is added or deleted. and I believe we can't remove a node id from a pool even if it is deleted

I checked the pool 1835 and it does include 5 node ids that are no longer alive.
https://explorer.testnet.grid.tf/api/v1/reservations/pools/1835
I created a new one on the same farm and it inlcuded the current live node.
https://explorer.testnet.grid.tf/api/v1/reservations/pools/2463
