### ISSUE TITLE
acme proxy for the 3bots

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#904]
We have a lot of subdomains and go over the Let's Encrypt limit.

Having a commercial subscription with another provider is a solution but having our account/api credentials spread out on every 3bot that requires a certificate is hardly a good idea 

The intention is to have  an acme server for the 3bot subdomains that's an acme client that uses an account with an ssl provider to acquire the certificates.

This way, our api key or eab credentials are only deployed on a single location and all 3bots that require certificates for can do so with default acme clients and without requiring special sensitive information.

No custom  certificate maintenance code has to be deployed on the 3bots nor any special checking if it is indeed a 3bot when handing out certificates since validation of the domain is exactly what acme does.

**Comment by abom** [comment]
I first got that we would just proxy the client requests from 3Bot to the CA provider and add the external binding key, but this is not possible as the requests are signed using the client private key, full details in RFC at https://tools.ietf.org/html/rfc8555#section-6.2.

Now for the following proposal:

> The intention is to have an acme server for the 3bot subdomains that's an acme client that uses an account with an ssl provider to acquire the certificates.

As as I understand, this will make us act as an acme server to 3Bots, while we do issue the certificate from the provider as a normal acme client and hand it over to to 3Bots. This won't work too because every client will generate a new key pair, this key pair will be used in the [Certificate singing request](https://tools.ietf.org/html/rfc2986) and it will be different from the client used in 3Bots, hence a the certificate will be invalid.

The following image is an overview for the acme protocol:
![acme-protocol](https://smallstep.com/uploads/acme-how-it-works.png)

By the client here I mostly mean `certbot`, which itself generates the key pair and configure the web server (nginx) with this key and the certificate it gets from the CA provider (the acme server which got the singing request with this key).

**Comment by robvanmieghem** [comment]
I was already afraid of this as I mentioned in https://github.com/threefoldtech/home/issues/875#issuecomment-702115867

**Comment by robvanmieghem** [comment]
@abom @m-motawea  Is it an option to implement the acme server ourselves and use the zerossl rest api?

**Comment by robvanmieghem** [comment]
I created another issue for this: https://github.com/threefoldtech/home/issues/905
