### ISSUE TITLE
Capacity Pool model should include the farm on which the pool was reserved.

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#915]
When creating a capacity pool one must define a farm at which the capacity will be reserved. However, after this step, the link between pool and farm seems to be lost. Model `Pool` doesn't reference the farm, and there don't seem to be any methods to work "down" to list pools for a farm.

As I understand it, Pools are "locked" to a single farm. Therefore they should indicate which farm they are part of in their identity.

**Comment by zaibon** [comment]
Conceptually a pool is just composed of a list of nodes. It is not really linked to a farm.
At this stage we have locked the pool to a single farm because of technical reasons, but on the long run we want pool to be able to spread over multiple farms. That's what we do not reference a specific farm within the pool type cause it will not be relevant in coming versions.

**Comment by OldhamMade** [comment]
> on the long run we want pool to be able to spread over multiple farms

Thanks for clarifying!
