### ISSUE TITLE
threefoldnow usable

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#918]
## websites

- now(2).threefold.io. -> suggest to use www_tfnow 
- marketplace(2).threefold.io -> suggest to also use www_tfnow 

both are websites so need to start with www_

## deliverables

- [ ] when update to repo -> automatic update of website & marketplace on production (development/master)
- [ ] there is no deployment chats for now, they link to a deployment welcome page
- [ ] welcome deployment page, explain that the marketplace will be part of your virtual system administrator called 3bot
- [ ] a registration page, so we know who is interested to play with it, capture interest, send email
- [ ] a script to install on ubuntu/osx
- [ ] a script to start on ubuntu/osx (development mode & production mode)
- [ ] each marketplace page (i) links to the commercial info on the wiki
- [ ] each deploy button links to the welcome deploy page
- [ ] a "howto" dir on the repo which is for ourselves with more info how to use, deploy, develop
- [ ] make sure the old repo's are gone or renamed

## remarks

- crystal tools has support for tmux and also triggers from github to start/upgrade something, ask info kristof if needed, best to use it
- no integration with 3bot connect, everyone can see
- the deployment wizards will not be used for now, we will make a package for them for a 3bot

**Comment by rkhamis** [comment]
There are several questions I have regarding this:

1. www_tfnow is a wiki not a website. shouldn't it be info_threefold_now as it was here (https://github.com/threefoldfoundation/info_threefold_now) but was changed to wiki_2020 which was the gridsome rewrite.

    I've archived info_threefold_now so it's clearly marked and renamed https://github.com/threefoldfoundation/wiki_2020 to https://github.com/threefoldfoundation/www_tfnow

   I've also created an issue here: https://github.com/threefoldfoundation/www_tfnow/issues/8 to have the branch names follow our conventions




2. marketplace is not a static website. it's a python package hosted in js-sdk. we can extract its code out yet
it will be a standalone package eventually but not yet. 
the biggest questions is **what is the intended usage of the marketplace**? if no deployments will take place centrally, does that mean that the marketplace will only be a landing page showcasing possible solutions?
if so, why do we even need it? shouldn't that be exactly what now.threefold.io is? we can add in now.threefold.io a button to subscribe to news regarding new solutions by allowing people to register their emails there.
please explain the intended behavior here.


3. regarding the automatic updating of the marketplace. that depends if the marketplace will be just a catalog of solutions (a reflection of the current now.threefold.io??) or current marketplace without login as described here: https://github.com/threefoldtech/js-sdk/issues/1467 


4. regarding the auto update of the www_tfnow, since it uses gridsome, static files need to be rebuilt each time there's an update. scripting this could potentially create errors in case of conflicts or badly updated files. how would you prefer this to be handled?


5. I've created two issues for the scripts:
https://github.com/threefoldfoundation/www_tfnow/issues/9 and https://github.com/threefoldfoundation/www_tfnow/issues/8

**Comment by rkhamis** [comment]
as agreed in call with @despiegk, we will not be changing the marketplace but issues created are still to be handled
