### ISSUE TITLE
GE: Customer Domain Routing

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#940]
We need to be able to route customer domains to containers.

- How will solution access points be created?
- Will it be like [Amazon Route 53?](https://aws.amazon.com/route53/)
- Will this include load balancing?
- How will it work in an edge-computing scenario? eg. GeoDNS/split-horizon
- How will SSL certificates be managed? eg. LetsEncrypt

**Comment by zaibon** [comment]
You can already do that part of this today by using the webgateway primitives.

1. The user delegate his domain or a part of his domdain to the web gateway: https://manual.threefold.io/#/capacity_domain_delegation
2. Create a proxy to route the traffic from the web gateway into the containers. https://manual.threefold.io/#/capacity_tcp_proxy https://manual.threefold.io/#/capacity_reverse_tcp_proxy

> How will SSL certificates be managed? eg. LetsEncrypt

It is not, and it should not. TLS can only terminate inside a user container. Any other solution would mean someone else then the user has a clear access to the data.
So usually the solution is to run a reverse proxy like nginx,caddy, HA proxy in a container and route the traffic to the rest of your backend running in other container over the wireguard private network.
This also answer you question about load balancing, since you handle the proxy, you also decide how you want to balance your traffic.
