### ISSUE TITLE
GE: Elastic Storage

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#943]
Customer's need their S3 reservation to grow automatically as their usage grows.

**Comment by gmachtel** [comment]
Is already available now. 
The point is not to make the zdb's too big or to change size of shards: this slows down the update, and it is a static configuration. 

Please don't prereserve all shards at once. it wastes storage which can't be used anymore.
Please DO make small shards (not eating much storage on back-end), then when you are at x% (ex. 70%) you **add** again new shards. Then the system will be able to use the new shards properly. 

No new minio head is needed for this extension. Only configuration file needs to be changed. All hooks are already available.

Planned for a prototype in VDC: automation of this Zero-stor configuration.

**Comment by OldhamMade** [comment]
> The point is not to make the zdb's too big or to change size of shards: this slows down the update, and it is a static configuration.
> 
> Please don't prereserve all shards at once. it wastes storage which can't be used anymore.
> Please DO make small shards (not eating much storage on back-end), then when you are at x% (ex. 70%) you **add** again new shards. Then the system will be able to use the new shards properly.

As mentioned, this is already understood.

> No new minio head is needed for this extension. Only configuration file needs to be changed. All hooks are already available.

Please provide documentation and example code on how to do this.

**Comment by gmachtel** [comment]
`Please provide documentation and example code on how to do this.`

Please have a look at the namespace in the 0-db repo: https://github.com/threefoldtech/0-db#namespaces

**Comment by gmachtel** [comment]
Also here the ideas currently tested out in the prototype on fuse interface can probably ease the way of working, more info on that next week.

**Comment by OldhamMade** [comment]
> Please have a look at the namespace in the 0-db repo: https://github.com/threefoldtech/0-db#namespaces

Apologies, but that is neither documentation nor example code, it is simply a description. I can't use that as a guide to increase storage space for an existing solution. 

Searching through that repository doesn't provide any guidance on how I would add more 0-db instances to a running minio container.

Please provide example code showing how this would be achieved.

**Comment by muhamadazmy** [comment]
Hey @OldhamMade. Since you aware the system is built using various components a full solution requires some steps at different levels. For example to be able to extend the capacity you could do the following
- Monitor the zdb namespaces this can be done by using the zdb API already linked by @gmachtel this information can give u how much of the namespace is used.
- Once you detect that more namespaces need to be added, your script can then go deploy the extra namespaces needed
- Once they have been deployed successfully, another operation to be done on minio level itself (by using the healer api provided here https://github.com/threefoldtech/minio/blob/meta/inode-and-history/cmd/gateway/zerostor/README.md#api) 
this call is required to actually make minio aware of the new shards.

I will try to provide an example code later, but not enough time atm
