### ISSUE TITLE
activation service protection

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#989]
because of the recent drainage

kds's suggestion is protect the activation service with  some sort of secret that is shared with all of the trusted services that need to create wallets 

- [x] activation service https://github.com/threefoldfoundation/tft-stellar/issues/254
- [ ] js-sdk https://github.com/threefoldtech/js-sdk/issues/2085
- [x] ~tfexplorer https://github.com/threefoldtech/tfexplorer/issues/262~
- [ ] tf connect https://github.com/threefoldtech/3Bot_connect/issues/182

**Comment by jdelrue** [comment]
@xmonader how would a shared secret fix the problem? We have a client side application, it would ultimately end up in the end users client code, which would be totally useless...

**Comment by despiegk** [comment]
@jdelrue even if would be in the code, it would still be ok, its not like people will reverse engineer an app to figure out a hidden (e.g. hashed) secret code for now.

and I am sure we can come up with other ways too, I can think of a couple of things

**Comment by robvanmieghem** [comment]
When looking at the last drainage ( for example https://stellar.expert/explorer/public/account/GAKATWD2RPABEAEMGWLLOY62KIFXVM3QTAX447DWG3BS3I6VRLVGE3XQ ) it is clear that the one who is doing this is not using the api but the mobile wallet or a 3bot UI since trustlines are created. If a hacker would use the api, he/she would not create the trustlines first. Adding a shared secret would not resolve this. It would also require disabling creating extra wallets.

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/tft-stellar/issues/256

**Comment by sasha-astiadi** [comment]
rob closed  threefoldfoundation/tft-stellar#254 as won’t fix
